/*
Check Point - SASE Public API

Testing StandardNetworksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perimeter81sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/CheckPointSW/perimeter-81-client-sdk/v3"
)

func Test_perimeter81sdk_StandardNetworksAPIService(t *testing.T) {

	// NewConfiguration here takes (apiKey, basePath): this SDK's hand-written
	// configuration.go (protected by .openapi-generator-ignore) replaced the
	// stock zero-arg NewConfiguration() with a two-arg constructor. The stock
	// api_test.mustache calls NewConfiguration() with no arguments, which no
	// longer compiles. Every test below is unconditionally t.Skip'd (it is
	// generated documentation, not an exercised regression test), so these
	// are placeholder values, never used against a real server.
	configuration := openapiclient.NewConfiguration("API_KEY", "BASE_PATH")
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StandardNetworksAPIService StandardGetInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var gatewayId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardGetInstance(context.Background(), networkId, gatewayId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardGetNetworks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardGetNetworks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2AddNetworkInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2AddNetworkInstance(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2DeleteNetworkInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2DeleteNetworkInstance(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2GetNetworkHealth", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2GetNetworkHealth(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2NetworkCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2NetworkCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2NetworkDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2NetworkDelete(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2NetworkFind", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2NetworkFind(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2NetworkUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2NetworkUpdate(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StandardNetworksAPIService StandardNetworksControllerV2Status", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var statusId string

		resp, httpRes, err := apiClient.StandardNetworksAPI.StandardNetworksControllerV2Status(context.Background(), statusId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
