/*
Check Point - SASE Public API

Testing StandardRouteTablesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perimeter81sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/CheckPointSW/perimeter-81-client-sdk/v3"
)

func Test_perimeter81sdk_StandardRouteTablesAPIService(t *testing.T) {

	// NewConfiguration here takes (apiKey, basePath): this SDK's hand-written
	// configuration.go (protected by .openapi-generator-ignore) replaced the
	// stock zero-arg NewConfiguration() with a two-arg constructor. The stock
	// api_test.mustache calls NewConfiguration() with no arguments, which no
	// longer compiles. Every test below is unconditionally t.Skip'd (it is
	// generated documentation, not an exercised regression test), so these
	// are placeholder values, never used against a real server.
	configuration := openapiclient.NewConfiguration("API_KEY", "BASE_PATH")
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StandardRouteTablesAPIService StandardGetRouteTable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.StandardRouteTablesAPI.StandardGetRouteTable(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
