/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the DeployNetworkPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeployNetworkPayload{}

// DeployNetworkPayload struct for DeployNetworkPayload
type DeployNetworkPayload struct {
	Network CreateNetworkPayload `json:"network"`
	// Region list.
	Regions []CreateRegionInNetworkPayload `json:"regions"`
	AdditionalProperties map[string]interface{}
}

type _DeployNetworkPayload DeployNetworkPayload

// NewDeployNetworkPayload instantiates a new DeployNetworkPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeployNetworkPayload(network CreateNetworkPayload, regions []CreateRegionInNetworkPayload) *DeployNetworkPayload {
	this := DeployNetworkPayload{}
	this.Network = network
	this.Regions = regions
	return &this
}

// NewDeployNetworkPayloadWithDefaults instantiates a new DeployNetworkPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployNetworkPayloadWithDefaults() *DeployNetworkPayload {
	this := DeployNetworkPayload{}
	return &this
}

// GetNetwork returns the Network field value
func (o *DeployNetworkPayload) GetNetwork() CreateNetworkPayload {
	if o == nil {
		var ret CreateNetworkPayload
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *DeployNetworkPayload) GetNetworkOk() (*CreateNetworkPayload, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *DeployNetworkPayload) SetNetwork(v CreateNetworkPayload) {
	o.Network = v
}

// GetRegions returns the Regions field value
func (o *DeployNetworkPayload) GetRegions() []CreateRegionInNetworkPayload {
	if o == nil {
		var ret []CreateRegionInNetworkPayload
		return ret
	}

	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value
// and a boolean to check if the value has been set.
func (o *DeployNetworkPayload) GetRegionsOk() ([]CreateRegionInNetworkPayload, bool) {
	if o == nil {
		return nil, false
	}
	return o.Regions, true
}

// SetRegions sets field value
func (o *DeployNetworkPayload) SetRegions(v []CreateRegionInNetworkPayload) {
	o.Regions = v
}

func (o DeployNetworkPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployNetworkPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	toSerialize["regions"] = o.Regions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeployNetworkPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
		"regions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeployNetworkPayload := _DeployNetworkPayload{}

	err = json.Unmarshal(data, &varDeployNetworkPayload)

	if err != nil {
		return err
	}

	*o = DeployNetworkPayload(varDeployNetworkPayload)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "network")
		delete(additionalProperties, "regions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeployNetworkPayload struct {
	value *DeployNetworkPayload
	isSet bool
}

func (v NullableDeployNetworkPayload) Get() *DeployNetworkPayload {
	return v.value
}

func (v *NullableDeployNetworkPayload) Set(val *DeployNetworkPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableDeployNetworkPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployNetworkPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployNetworkPayload(val *DeployNetworkPayload) *NullableDeployNetworkPayload {
	return &NullableDeployNetworkPayload{value: val, isSet: true}
}

func (v NullableDeployNetworkPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployNetworkPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


