/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the NetworkFeaturesCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkFeaturesCreate{}

// NetworkFeaturesCreate struct for NetworkFeaturesCreate
type NetworkFeaturesCreate struct {
	CloudSecurity NetworkFeaturesCloudSecurity `json:"cloudSecurity"`
	SymmetricInnerMesh NetworkFeaturesCloudSecurity `json:"symmetricInnerMesh"`
	DNSServices NetworkFeaturesDNSServices `json:"DNSServices"`
	AdditionalProperties map[string]interface{}
}

type _NetworkFeaturesCreate NetworkFeaturesCreate

// NewNetworkFeaturesCreate instantiates a new NetworkFeaturesCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkFeaturesCreate(cloudSecurity NetworkFeaturesCloudSecurity, symmetricInnerMesh NetworkFeaturesCloudSecurity, dNSServices NetworkFeaturesDNSServices) *NetworkFeaturesCreate {
	this := NetworkFeaturesCreate{}
	this.CloudSecurity = cloudSecurity
	this.SymmetricInnerMesh = symmetricInnerMesh
	this.DNSServices = dNSServices
	return &this
}

// NewNetworkFeaturesCreateWithDefaults instantiates a new NetworkFeaturesCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkFeaturesCreateWithDefaults() *NetworkFeaturesCreate {
	this := NetworkFeaturesCreate{}
	return &this
}

// GetCloudSecurity returns the CloudSecurity field value
func (o *NetworkFeaturesCreate) GetCloudSecurity() NetworkFeaturesCloudSecurity {
	if o == nil {
		var ret NetworkFeaturesCloudSecurity
		return ret
	}

	return o.CloudSecurity
}

// GetCloudSecurityOk returns a tuple with the CloudSecurity field value
// and a boolean to check if the value has been set.
func (o *NetworkFeaturesCreate) GetCloudSecurityOk() (*NetworkFeaturesCloudSecurity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudSecurity, true
}

// SetCloudSecurity sets field value
func (o *NetworkFeaturesCreate) SetCloudSecurity(v NetworkFeaturesCloudSecurity) {
	o.CloudSecurity = v
}

// GetSymmetricInnerMesh returns the SymmetricInnerMesh field value
func (o *NetworkFeaturesCreate) GetSymmetricInnerMesh() NetworkFeaturesCloudSecurity {
	if o == nil {
		var ret NetworkFeaturesCloudSecurity
		return ret
	}

	return o.SymmetricInnerMesh
}

// GetSymmetricInnerMeshOk returns a tuple with the SymmetricInnerMesh field value
// and a boolean to check if the value has been set.
func (o *NetworkFeaturesCreate) GetSymmetricInnerMeshOk() (*NetworkFeaturesCloudSecurity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SymmetricInnerMesh, true
}

// SetSymmetricInnerMesh sets field value
func (o *NetworkFeaturesCreate) SetSymmetricInnerMesh(v NetworkFeaturesCloudSecurity) {
	o.SymmetricInnerMesh = v
}

// GetDNSServices returns the DNSServices field value
func (o *NetworkFeaturesCreate) GetDNSServices() NetworkFeaturesDNSServices {
	if o == nil {
		var ret NetworkFeaturesDNSServices
		return ret
	}

	return o.DNSServices
}

// GetDNSServicesOk returns a tuple with the DNSServices field value
// and a boolean to check if the value has been set.
func (o *NetworkFeaturesCreate) GetDNSServicesOk() (*NetworkFeaturesDNSServices, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DNSServices, true
}

// SetDNSServices sets field value
func (o *NetworkFeaturesCreate) SetDNSServices(v NetworkFeaturesDNSServices) {
	o.DNSServices = v
}

func (o NetworkFeaturesCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkFeaturesCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloudSecurity"] = o.CloudSecurity
	toSerialize["symmetricInnerMesh"] = o.SymmetricInnerMesh
	toSerialize["DNSServices"] = o.DNSServices

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetworkFeaturesCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloudSecurity",
		"symmetricInnerMesh",
		"DNSServices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkFeaturesCreate := _NetworkFeaturesCreate{}

	err = json.Unmarshal(data, &varNetworkFeaturesCreate)

	if err != nil {
		return err
	}

	*o = NetworkFeaturesCreate(varNetworkFeaturesCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cloudSecurity")
		delete(additionalProperties, "symmetricInnerMesh")
		delete(additionalProperties, "DNSServices")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetworkFeaturesCreate struct {
	value *NetworkFeaturesCreate
	isSet bool
}

func (v NullableNetworkFeaturesCreate) Get() *NetworkFeaturesCreate {
	return v.value
}

func (v *NullableNetworkFeaturesCreate) Set(val *NetworkFeaturesCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkFeaturesCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkFeaturesCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkFeaturesCreate(val *NetworkFeaturesCreate) *NullableNetworkFeaturesCreate {
	return &NullableNetworkFeaturesCreate{value: val, isSet: true}
}

func (v NullableNetworkFeaturesCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkFeaturesCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


