/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// ObjectServiceProtocolOptionsICMPrequest -1 means 'any', the rest of the values are the RFC default ICMP parameters
type ObjectServiceProtocolOptionsICMPrequest int32

// List of ObjectServiceProtocolOptionsICMPrequest
const (
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__MINUS_1 ObjectServiceProtocolOptionsICMPrequest = -1
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__0 ObjectServiceProtocolOptionsICMPrequest = 0
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__3 ObjectServiceProtocolOptionsICMPrequest = 3
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__5 ObjectServiceProtocolOptionsICMPrequest = 5
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__8 ObjectServiceProtocolOptionsICMPrequest = 8
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__9 ObjectServiceProtocolOptionsICMPrequest = 9
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__10 ObjectServiceProtocolOptionsICMPrequest = 10
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__11 ObjectServiceProtocolOptionsICMPrequest = 11
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__12 ObjectServiceProtocolOptionsICMPrequest = 12
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__13 ObjectServiceProtocolOptionsICMPrequest = 13
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__14 ObjectServiceProtocolOptionsICMPrequest = 14
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__40 ObjectServiceProtocolOptionsICMPrequest = 40
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__42 ObjectServiceProtocolOptionsICMPrequest = 42
	OBJECTSERVICEPROTOCOLOPTIONSICMPREQUEST__43 ObjectServiceProtocolOptionsICMPrequest = 43
)

// All allowed values of ObjectServiceProtocolOptionsICMPrequest enum
var AllowedObjectServiceProtocolOptionsICMPrequestEnumValues = []ObjectServiceProtocolOptionsICMPrequest{
	-1,
	0,
	3,
	5,
	8,
	9,
	10,
	11,
	12,
	13,
	14,
	40,
	42,
	43,
}

func (v *ObjectServiceProtocolOptionsICMPrequest) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ObjectServiceProtocolOptionsICMPrequest(value)
	for _, existing := range AllowedObjectServiceProtocolOptionsICMPrequestEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ObjectServiceProtocolOptionsICMPrequest", value)
}

// NewObjectServiceProtocolOptionsICMPrequestFromValue returns a pointer to a valid ObjectServiceProtocolOptionsICMPrequest
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewObjectServiceProtocolOptionsICMPrequestFromValue(v int32) (*ObjectServiceProtocolOptionsICMPrequest, error) {
	ev := ObjectServiceProtocolOptionsICMPrequest(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ObjectServiceProtocolOptionsICMPrequest: valid values are %v", v, AllowedObjectServiceProtocolOptionsICMPrequestEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ObjectServiceProtocolOptionsICMPrequest) IsValid() bool {
	for _, existing := range AllowedObjectServiceProtocolOptionsICMPrequestEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ObjectServiceProtocolOptionsICMPrequest value
func (v ObjectServiceProtocolOptionsICMPrequest) Ptr() *ObjectServiceProtocolOptionsICMPrequest {
	return &v
}

type NullableObjectServiceProtocolOptionsICMPrequest struct {
	value *ObjectServiceProtocolOptionsICMPrequest
	isSet bool
}

func (v NullableObjectServiceProtocolOptionsICMPrequest) Get() *ObjectServiceProtocolOptionsICMPrequest {
	return v.value
}

func (v *NullableObjectServiceProtocolOptionsICMPrequest) Set(val *ObjectServiceProtocolOptionsICMPrequest) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectServiceProtocolOptionsICMPrequest) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectServiceProtocolOptionsICMPrequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectServiceProtocolOptionsICMPrequest(val *ObjectServiceProtocolOptionsICMPrequest) *NullableObjectServiceProtocolOptionsICMPrequest {
	return &NullableObjectServiceProtocolOptionsICMPrequest{value: val, isSet: true}
}

func (v NullableObjectServiceProtocolOptionsICMPrequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectServiceProtocolOptionsICMPrequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

