/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the UpdateSplitTunnelingConfigurationAsync409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSplitTunnelingConfigurationAsync409Response{}

// UpdateSplitTunnelingConfigurationAsync409Response struct for UpdateSplitTunnelingConfigurationAsync409Response
type UpdateSplitTunnelingConfigurationAsync409Response struct {
	Status *int32 `json:"status,omitempty"`
	// Error message code
	Message *string `json:"message,omitempty"`
	MessageCode *string `json:"messageCode,omitempty"`
	// Additional error context
	Data map[string]interface{} `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateSplitTunnelingConfigurationAsync409Response UpdateSplitTunnelingConfigurationAsync409Response

// NewUpdateSplitTunnelingConfigurationAsync409Response instantiates a new UpdateSplitTunnelingConfigurationAsync409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSplitTunnelingConfigurationAsync409Response() *UpdateSplitTunnelingConfigurationAsync409Response {
	this := UpdateSplitTunnelingConfigurationAsync409Response{}
	return &this
}

// NewUpdateSplitTunnelingConfigurationAsync409ResponseWithDefaults instantiates a new UpdateSplitTunnelingConfigurationAsync409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSplitTunnelingConfigurationAsync409ResponseWithDefaults() *UpdateSplitTunnelingConfigurationAsync409Response {
	this := UpdateSplitTunnelingConfigurationAsync409Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) SetStatus(v int32) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) SetMessage(v string) {
	o.Message = &v
}

// GetMessageCode returns the MessageCode field value if set, zero value otherwise.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetMessageCode() string {
	if o == nil || IsNil(o.MessageCode) {
		var ret string
		return ret
	}
	return *o.MessageCode
}

// GetMessageCodeOk returns a tuple with the MessageCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetMessageCodeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageCode) {
		return nil, false
	}
	return o.MessageCode, true
}

// HasMessageCode returns a boolean if a field has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) HasMessageCode() bool {
	if o != nil && !IsNil(o.MessageCode) {
		return true
	}

	return false
}

// SetMessageCode gets a reference to the given string and assigns it to the MessageCode field.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) SetMessageCode(v string) {
	o.MessageCode = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *UpdateSplitTunnelingConfigurationAsync409Response) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o UpdateSplitTunnelingConfigurationAsync409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSplitTunnelingConfigurationAsync409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.MessageCode) {
		toSerialize["messageCode"] = o.MessageCode
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateSplitTunnelingConfigurationAsync409Response) UnmarshalJSON(data []byte) (err error) {
	varUpdateSplitTunnelingConfigurationAsync409Response := _UpdateSplitTunnelingConfigurationAsync409Response{}

	err = json.Unmarshal(data, &varUpdateSplitTunnelingConfigurationAsync409Response)

	if err != nil {
		return err
	}

	*o = UpdateSplitTunnelingConfigurationAsync409Response(varUpdateSplitTunnelingConfigurationAsync409Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "message")
		delete(additionalProperties, "messageCode")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateSplitTunnelingConfigurationAsync409Response struct {
	value *UpdateSplitTunnelingConfigurationAsync409Response
	isSet bool
}

func (v NullableUpdateSplitTunnelingConfigurationAsync409Response) Get() *UpdateSplitTunnelingConfigurationAsync409Response {
	return v.value
}

func (v *NullableUpdateSplitTunnelingConfigurationAsync409Response) Set(val *UpdateSplitTunnelingConfigurationAsync409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSplitTunnelingConfigurationAsync409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSplitTunnelingConfigurationAsync409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSplitTunnelingConfigurationAsync409Response(val *UpdateSplitTunnelingConfigurationAsync409Response) *NullableUpdateSplitTunnelingConfigurationAsync409Response {
	return &NullableUpdateSplitTunnelingConfigurationAsync409Response{value: val, isSet: true}
}

func (v NullableUpdateSplitTunnelingConfigurationAsync409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSplitTunnelingConfigurationAsync409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


