/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SupportOptionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportOptionsRequest{}

// SupportOptionsRequest End users support information settings
type SupportOptionsRequest struct {
	// Type of phone support: - harmonySaseDefault: Use Harmony SASE default phone support - custom: Use custom phone numbers (requires supportPhoneNumbers) - hidden: Disable phone support 
	PhoneSupportType string `json:"phoneSupportType"`
	// Custom phone numbers array (1-3 items). Required when phoneSupportType is 'custom'. Must be null or omitted when phoneSupportType is not 'custom'. 
	SupportPhoneNumbers []SupportPhoneNumber `json:"supportPhoneNumbers,omitempty"`
	// Enable or disable user guides and documentation
	UserGuidesEnabled bool `json:"userGuidesEnabled"`
	// Type of live chat support: - harmonySaseDefault: Use Harmony SASE default chat - custom: Use custom chat URL (requires liveChatCustomUrl) - hidden: Disable live chat support 
	LiveChatType string `json:"liveChatType"`
	LiveChatCustomUrl *string `json:"liveChatCustomUrl,omitempty"`
}

type _SupportOptionsRequest SupportOptionsRequest

// NewSupportOptionsRequest instantiates a new SupportOptionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportOptionsRequest(phoneSupportType string, userGuidesEnabled bool, liveChatType string) *SupportOptionsRequest {
	this := SupportOptionsRequest{}
	this.PhoneSupportType = phoneSupportType
	this.UserGuidesEnabled = userGuidesEnabled
	this.LiveChatType = liveChatType
	return &this
}

// NewSupportOptionsRequestWithDefaults instantiates a new SupportOptionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportOptionsRequestWithDefaults() *SupportOptionsRequest {
	this := SupportOptionsRequest{}
	return &this
}

// GetPhoneSupportType returns the PhoneSupportType field value
func (o *SupportOptionsRequest) GetPhoneSupportType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneSupportType
}

// GetPhoneSupportTypeOk returns a tuple with the PhoneSupportType field value
// and a boolean to check if the value has been set.
func (o *SupportOptionsRequest) GetPhoneSupportTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneSupportType, true
}

// SetPhoneSupportType sets field value
func (o *SupportOptionsRequest) SetPhoneSupportType(v string) {
	o.PhoneSupportType = v
}

// GetSupportPhoneNumbers returns the SupportPhoneNumbers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SupportOptionsRequest) GetSupportPhoneNumbers() []SupportPhoneNumber {
	if o == nil {
		var ret []SupportPhoneNumber
		return ret
	}
	return o.SupportPhoneNumbers
}

// GetSupportPhoneNumbersOk returns a tuple with the SupportPhoneNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SupportOptionsRequest) GetSupportPhoneNumbersOk() ([]SupportPhoneNumber, bool) {
	if o == nil || IsNil(o.SupportPhoneNumbers) {
		return nil, false
	}
	return o.SupportPhoneNumbers, true
}

// HasSupportPhoneNumbers returns a boolean if a field has been set.
func (o *SupportOptionsRequest) HasSupportPhoneNumbers() bool {
	if o != nil && !IsNil(o.SupportPhoneNumbers) {
		return true
	}

	return false
}

// SetSupportPhoneNumbers gets a reference to the given []SupportPhoneNumber and assigns it to the SupportPhoneNumbers field.
func (o *SupportOptionsRequest) SetSupportPhoneNumbers(v []SupportPhoneNumber) {
	o.SupportPhoneNumbers = v
}

// GetUserGuidesEnabled returns the UserGuidesEnabled field value
func (o *SupportOptionsRequest) GetUserGuidesEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UserGuidesEnabled
}

// GetUserGuidesEnabledOk returns a tuple with the UserGuidesEnabled field value
// and a boolean to check if the value has been set.
func (o *SupportOptionsRequest) GetUserGuidesEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserGuidesEnabled, true
}

// SetUserGuidesEnabled sets field value
func (o *SupportOptionsRequest) SetUserGuidesEnabled(v bool) {
	o.UserGuidesEnabled = v
}

// GetLiveChatType returns the LiveChatType field value
func (o *SupportOptionsRequest) GetLiveChatType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiveChatType
}

// GetLiveChatTypeOk returns a tuple with the LiveChatType field value
// and a boolean to check if the value has been set.
func (o *SupportOptionsRequest) GetLiveChatTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiveChatType, true
}

// SetLiveChatType sets field value
func (o *SupportOptionsRequest) SetLiveChatType(v string) {
	o.LiveChatType = v
}

// GetLiveChatCustomUrl returns the LiveChatCustomUrl field value if set, zero value otherwise.
func (o *SupportOptionsRequest) GetLiveChatCustomUrl() string {
	if o == nil || IsNil(o.LiveChatCustomUrl) {
		var ret string
		return ret
	}
	return *o.LiveChatCustomUrl
}

// GetLiveChatCustomUrlOk returns a tuple with the LiveChatCustomUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportOptionsRequest) GetLiveChatCustomUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LiveChatCustomUrl) {
		return nil, false
	}
	return o.LiveChatCustomUrl, true
}

// HasLiveChatCustomUrl returns a boolean if a field has been set.
func (o *SupportOptionsRequest) HasLiveChatCustomUrl() bool {
	if o != nil && !IsNil(o.LiveChatCustomUrl) {
		return true
	}

	return false
}

// SetLiveChatCustomUrl gets a reference to the given string and assigns it to the LiveChatCustomUrl field.
func (o *SupportOptionsRequest) SetLiveChatCustomUrl(v string) {
	o.LiveChatCustomUrl = &v
}

func (o SupportOptionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportOptionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phoneSupportType"] = o.PhoneSupportType
	if o.SupportPhoneNumbers != nil {
		toSerialize["supportPhoneNumbers"] = o.SupportPhoneNumbers
	}
	toSerialize["userGuidesEnabled"] = o.UserGuidesEnabled
	toSerialize["liveChatType"] = o.LiveChatType
	if !IsNil(o.LiveChatCustomUrl) {
		toSerialize["liveChatCustomUrl"] = o.LiveChatCustomUrl
	}
	return toSerialize, nil
}

func (o *SupportOptionsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phoneSupportType",
		"userGuidesEnabled",
		"liveChatType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSupportOptionsRequest := _SupportOptionsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSupportOptionsRequest)

	if err != nil {
		return err
	}

	*o = SupportOptionsRequest(varSupportOptionsRequest)

	return err
}

type NullableSupportOptionsRequest struct {
	value *SupportOptionsRequest
	isSet bool
}

func (v NullableSupportOptionsRequest) Get() *SupportOptionsRequest {
	return v.value
}

func (v *NullableSupportOptionsRequest) Set(val *SupportOptionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportOptionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportOptionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportOptionsRequest(val *SupportOptionsRequest) *NullableSupportOptionsRequest {
	return &NullableSupportOptionsRequest{value: val, isSet: true}
}

func (v NullableSupportOptionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportOptionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


