/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ConditionValueInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConditionValueInner{}

// ConditionValueInner struct for ConditionValueInner
type ConditionValueInner struct {
	Weekdays []string `json:"weekdays"`
	StartTime ConditionTime `json:"startTime"`
	EndTime ConditionTime `json:"endTime"`
	AdditionalProperties map[string]interface{}
}

type _ConditionValueInner ConditionValueInner

// NewConditionValueInner instantiates a new ConditionValueInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConditionValueInner(weekdays []string, startTime ConditionTime, endTime ConditionTime) *ConditionValueInner {
	this := ConditionValueInner{}
	this.Weekdays = weekdays
	this.StartTime = startTime
	this.EndTime = endTime
	return &this
}

// NewConditionValueInnerWithDefaults instantiates a new ConditionValueInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConditionValueInnerWithDefaults() *ConditionValueInner {
	this := ConditionValueInner{}
	return &this
}

// GetWeekdays returns the Weekdays field value
func (o *ConditionValueInner) GetWeekdays() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Weekdays
}

// GetWeekdaysOk returns a tuple with the Weekdays field value
// and a boolean to check if the value has been set.
func (o *ConditionValueInner) GetWeekdaysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Weekdays, true
}

// SetWeekdays sets field value
func (o *ConditionValueInner) SetWeekdays(v []string) {
	o.Weekdays = v
}

// GetStartTime returns the StartTime field value
func (o *ConditionValueInner) GetStartTime() ConditionTime {
	if o == nil {
		var ret ConditionTime
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *ConditionValueInner) GetStartTimeOk() (*ConditionTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *ConditionValueInner) SetStartTime(v ConditionTime) {
	o.StartTime = v
}

// GetEndTime returns the EndTime field value
func (o *ConditionValueInner) GetEndTime() ConditionTime {
	if o == nil {
		var ret ConditionTime
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *ConditionValueInner) GetEndTimeOk() (*ConditionTime, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *ConditionValueInner) SetEndTime(v ConditionTime) {
	o.EndTime = v
}

func (o ConditionValueInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConditionValueInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["weekdays"] = o.Weekdays
	toSerialize["startTime"] = o.StartTime
	toSerialize["endTime"] = o.EndTime

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConditionValueInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"weekdays",
		"startTime",
		"endTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConditionValueInner := _ConditionValueInner{}

	err = json.Unmarshal(data, &varConditionValueInner)

	if err != nil {
		return err
	}

	*o = ConditionValueInner(varConditionValueInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "weekdays")
		delete(additionalProperties, "startTime")
		delete(additionalProperties, "endTime")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConditionValueInner struct {
	value *ConditionValueInner
	isSet bool
}

func (v NullableConditionValueInner) Get() *ConditionValueInner {
	return v.value
}

func (v *NullableConditionValueInner) Set(val *ConditionValueInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConditionValueInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConditionValueInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConditionValueInner(val *ConditionValueInner) *NullableConditionValueInner {
	return &NullableConditionValueInner{value: val, isSet: true}
}

func (v NullableConditionValueInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConditionValueInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


