/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GumCreateCustomRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GumCreateCustomRoleRequest{}

// GumCreateCustomRoleRequest struct for GumCreateCustomRoleRequest
type GumCreateCustomRoleRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Categories []CategoryEntry `json:"categories"`
	AdditionalProperties map[string]interface{}
}

type _GumCreateCustomRoleRequest GumCreateCustomRoleRequest

// NewGumCreateCustomRoleRequest instantiates a new GumCreateCustomRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGumCreateCustomRoleRequest(name string, categories []CategoryEntry) *GumCreateCustomRoleRequest {
	this := GumCreateCustomRoleRequest{}
	this.Name = name
	this.Categories = categories
	return &this
}

// NewGumCreateCustomRoleRequestWithDefaults instantiates a new GumCreateCustomRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGumCreateCustomRoleRequestWithDefaults() *GumCreateCustomRoleRequest {
	this := GumCreateCustomRoleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *GumCreateCustomRoleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GumCreateCustomRoleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GumCreateCustomRoleRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GumCreateCustomRoleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GumCreateCustomRoleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GumCreateCustomRoleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GumCreateCustomRoleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetCategories returns the Categories field value
func (o *GumCreateCustomRoleRequest) GetCategories() []CategoryEntry {
	if o == nil {
		var ret []CategoryEntry
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *GumCreateCustomRoleRequest) GetCategoriesOk() ([]CategoryEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *GumCreateCustomRoleRequest) SetCategories(v []CategoryEntry) {
	o.Categories = v
}

func (o GumCreateCustomRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GumCreateCustomRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["categories"] = o.Categories

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GumCreateCustomRoleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"categories",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGumCreateCustomRoleRequest := _GumCreateCustomRoleRequest{}

	err = json.Unmarshal(data, &varGumCreateCustomRoleRequest)

	if err != nil {
		return err
	}

	*o = GumCreateCustomRoleRequest(varGumCreateCustomRoleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "categories")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGumCreateCustomRoleRequest struct {
	value *GumCreateCustomRoleRequest
	isSet bool
}

func (v NullableGumCreateCustomRoleRequest) Get() *GumCreateCustomRoleRequest {
	return v.value
}

func (v *NullableGumCreateCustomRoleRequest) Set(val *GumCreateCustomRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGumCreateCustomRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGumCreateCustomRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGumCreateCustomRoleRequest(val *GumCreateCustomRoleRequest) *NullableGumCreateCustomRoleRequest {
	return &NullableGumCreateCustomRoleRequest{value: val, isSet: true}
}

func (v NullableGumCreateCustomRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGumCreateCustomRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


