/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the HttpsInspectionRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpsInspectionRule{}

// HttpsInspectionRule struct for HttpsInspectionRule
type HttpsInspectionRule struct {
	// Rule ID (optional in requests, auto-generated for new rules)
	Id *string `json:"id,omitempty"`
	// Rule name (cannot contain < or > characters)
	Name string `json:"name" validate:"regexp=^[^<>]+$"`
	// Where the rule is applied: Agents, Sites, or Both
	AppliedOn string `json:"appliedOn"`
	// Rule priority. Updated automatically when rules are created/updated
	Priority int32 `json:"priority"`
	// List of source objects
	Sources []HttpsInspectionSource `json:"sources"`
	// List of destination objects
	Destinations []HttpsInspectionDestination `json:"destinations"`
	// Bypass or HTTPS Inspection action (optional, default: 'bypass'). 'inspect' is always valid for 'sites' appliedOn. When the Inspection Policy feature is enabled, 'inspect' is also valid on 'agents' and 'both'. 'inspectNoDecrypt' requires the Inspection Policy feature and is only valid on 'agents' appliedOn (rejected on 'sites' and 'both' regardless of the feature).
	Action *string `json:"action,omitempty"`
	// HTTPS Inspection logging (optional) is disabled by default and is supported only for rules applied to agents
	Log *string `json:"log,omitempty"`
	// Rule status
	Status string `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _HttpsInspectionRule HttpsInspectionRule

// NewHttpsInspectionRule instantiates a new HttpsInspectionRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpsInspectionRule(name string, appliedOn string, priority int32, sources []HttpsInspectionSource, destinations []HttpsInspectionDestination, status string) *HttpsInspectionRule {
	this := HttpsInspectionRule{}
	this.Name = name
	this.AppliedOn = appliedOn
	this.Priority = priority
	this.Sources = sources
	this.Destinations = destinations
	this.Status = status
	return &this
}

// NewHttpsInspectionRuleWithDefaults instantiates a new HttpsInspectionRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpsInspectionRuleWithDefaults() *HttpsInspectionRule {
	this := HttpsInspectionRule{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *HttpsInspectionRule) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *HttpsInspectionRule) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *HttpsInspectionRule) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *HttpsInspectionRule) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HttpsInspectionRule) SetName(v string) {
	o.Name = v
}

// GetAppliedOn returns the AppliedOn field value
func (o *HttpsInspectionRule) GetAppliedOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppliedOn
}

// GetAppliedOnOk returns a tuple with the AppliedOn field value
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetAppliedOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppliedOn, true
}

// SetAppliedOn sets field value
func (o *HttpsInspectionRule) SetAppliedOn(v string) {
	o.AppliedOn = v
}

// GetPriority returns the Priority field value
func (o *HttpsInspectionRule) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *HttpsInspectionRule) SetPriority(v int32) {
	o.Priority = v
}

// GetSources returns the Sources field value
func (o *HttpsInspectionRule) GetSources() []HttpsInspectionSource {
	if o == nil {
		var ret []HttpsInspectionSource
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetSourcesOk() ([]HttpsInspectionSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sources, true
}

// SetSources sets field value
func (o *HttpsInspectionRule) SetSources(v []HttpsInspectionSource) {
	o.Sources = v
}

// GetDestinations returns the Destinations field value
func (o *HttpsInspectionRule) GetDestinations() []HttpsInspectionDestination {
	if o == nil {
		var ret []HttpsInspectionDestination
		return ret
	}

	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetDestinationsOk() ([]HttpsInspectionDestination, bool) {
	if o == nil {
		return nil, false
	}
	return o.Destinations, true
}

// SetDestinations sets field value
func (o *HttpsInspectionRule) SetDestinations(v []HttpsInspectionDestination) {
	o.Destinations = v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *HttpsInspectionRule) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *HttpsInspectionRule) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *HttpsInspectionRule) SetAction(v string) {
	o.Action = &v
}

// GetLog returns the Log field value if set, zero value otherwise.
func (o *HttpsInspectionRule) GetLog() string {
	if o == nil || IsNil(o.Log) {
		var ret string
		return ret
	}
	return *o.Log
}

// GetLogOk returns a tuple with the Log field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetLogOk() (*string, bool) {
	if o == nil || IsNil(o.Log) {
		return nil, false
	}
	return o.Log, true
}

// HasLog returns a boolean if a field has been set.
func (o *HttpsInspectionRule) HasLog() bool {
	if o != nil && !IsNil(o.Log) {
		return true
	}

	return false
}

// SetLog gets a reference to the given string and assigns it to the Log field.
func (o *HttpsInspectionRule) SetLog(v string) {
	o.Log = &v
}

// GetStatus returns the Status field value
func (o *HttpsInspectionRule) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HttpsInspectionRule) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HttpsInspectionRule) SetStatus(v string) {
	o.Status = v
}

func (o HttpsInspectionRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpsInspectionRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["appliedOn"] = o.AppliedOn
	toSerialize["priority"] = o.Priority
	toSerialize["sources"] = o.Sources
	toSerialize["destinations"] = o.Destinations
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Log) {
		toSerialize["log"] = o.Log
	}
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HttpsInspectionRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"appliedOn",
		"priority",
		"sources",
		"destinations",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHttpsInspectionRule := _HttpsInspectionRule{}

	err = json.Unmarshal(data, &varHttpsInspectionRule)

	if err != nil {
		return err
	}

	*o = HttpsInspectionRule(varHttpsInspectionRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "appliedOn")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "sources")
		delete(additionalProperties, "destinations")
		delete(additionalProperties, "action")
		delete(additionalProperties, "log")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHttpsInspectionRule struct {
	value *HttpsInspectionRule
	isSet bool
}

func (v NullableHttpsInspectionRule) Get() *HttpsInspectionRule {
	return v.value
}

func (v *NullableHttpsInspectionRule) Set(val *HttpsInspectionRule) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpsInspectionRule) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpsInspectionRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpsInspectionRule(val *HttpsInspectionRule) *NullableHttpsInspectionRule {
	return &NullableHttpsInspectionRule{value: val, isSet: true}
}

func (v NullableHttpsInspectionRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpsInspectionRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


