/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the DnsPolicyResponseAllOfPrivate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DnsPolicyResponseAllOfPrivate{}

// DnsPolicyResponseAllOfPrivate struct for DnsPolicyResponseAllOfPrivate
type DnsPolicyResponseAllOfPrivate struct {
	// Indicates whether DNS updates (RFC 2136) are forwarded to the private DNS servers
	ForwardDNSUpdate *bool `json:"forwardDNSUpdate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DnsPolicyResponseAllOfPrivate DnsPolicyResponseAllOfPrivate

// NewDnsPolicyResponseAllOfPrivate instantiates a new DnsPolicyResponseAllOfPrivate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnsPolicyResponseAllOfPrivate() *DnsPolicyResponseAllOfPrivate {
	this := DnsPolicyResponseAllOfPrivate{}
	return &this
}

// NewDnsPolicyResponseAllOfPrivateWithDefaults instantiates a new DnsPolicyResponseAllOfPrivate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnsPolicyResponseAllOfPrivateWithDefaults() *DnsPolicyResponseAllOfPrivate {
	this := DnsPolicyResponseAllOfPrivate{}
	return &this
}

// GetForwardDNSUpdate returns the ForwardDNSUpdate field value if set, zero value otherwise.
func (o *DnsPolicyResponseAllOfPrivate) GetForwardDNSUpdate() bool {
	if o == nil || IsNil(o.ForwardDNSUpdate) {
		var ret bool
		return ret
	}
	return *o.ForwardDNSUpdate
}

// GetForwardDNSUpdateOk returns a tuple with the ForwardDNSUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnsPolicyResponseAllOfPrivate) GetForwardDNSUpdateOk() (*bool, bool) {
	if o == nil || IsNil(o.ForwardDNSUpdate) {
		return nil, false
	}
	return o.ForwardDNSUpdate, true
}

// HasForwardDNSUpdate returns a boolean if a field has been set.
func (o *DnsPolicyResponseAllOfPrivate) HasForwardDNSUpdate() bool {
	if o != nil && !IsNil(o.ForwardDNSUpdate) {
		return true
	}

	return false
}

// SetForwardDNSUpdate gets a reference to the given bool and assigns it to the ForwardDNSUpdate field.
func (o *DnsPolicyResponseAllOfPrivate) SetForwardDNSUpdate(v bool) {
	o.ForwardDNSUpdate = &v
}

func (o DnsPolicyResponseAllOfPrivate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DnsPolicyResponseAllOfPrivate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ForwardDNSUpdate) {
		toSerialize["forwardDNSUpdate"] = o.ForwardDNSUpdate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DnsPolicyResponseAllOfPrivate) UnmarshalJSON(data []byte) (err error) {
	varDnsPolicyResponseAllOfPrivate := _DnsPolicyResponseAllOfPrivate{}

	err = json.Unmarshal(data, &varDnsPolicyResponseAllOfPrivate)

	if err != nil {
		return err
	}

	*o = DnsPolicyResponseAllOfPrivate(varDnsPolicyResponseAllOfPrivate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "forwardDNSUpdate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDnsPolicyResponseAllOfPrivate struct {
	value *DnsPolicyResponseAllOfPrivate
	isSet bool
}

func (v NullableDnsPolicyResponseAllOfPrivate) Get() *DnsPolicyResponseAllOfPrivate {
	return v.value
}

func (v *NullableDnsPolicyResponseAllOfPrivate) Set(val *DnsPolicyResponseAllOfPrivate) {
	v.value = val
	v.isSet = true
}

func (v NullableDnsPolicyResponseAllOfPrivate) IsSet() bool {
	return v.isSet
}

func (v *NullableDnsPolicyResponseAllOfPrivate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnsPolicyResponseAllOfPrivate(val *DnsPolicyResponseAllOfPrivate) *NullableDnsPolicyResponseAllOfPrivate {
	return &NullableDnsPolicyResponseAllOfPrivate{value: val, isSet: true}
}

func (v NullableDnsPolicyResponseAllOfPrivate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnsPolicyResponseAllOfPrivate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


