/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the UpdateAccessPolicyRulesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAccessPolicyRulesResponse{}

// UpdateAccessPolicyRulesResponse struct for UpdateAccessPolicyRulesResponse
type UpdateAccessPolicyRulesResponse struct {
	Status *int32 `json:"status,omitempty"`
	Data *AccessPolicyRulesGetResponseData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAccessPolicyRulesResponse UpdateAccessPolicyRulesResponse

// NewUpdateAccessPolicyRulesResponse instantiates a new UpdateAccessPolicyRulesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAccessPolicyRulesResponse() *UpdateAccessPolicyRulesResponse {
	this := UpdateAccessPolicyRulesResponse{}
	return &this
}

// NewUpdateAccessPolicyRulesResponseWithDefaults instantiates a new UpdateAccessPolicyRulesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAccessPolicyRulesResponseWithDefaults() *UpdateAccessPolicyRulesResponse {
	this := UpdateAccessPolicyRulesResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdateAccessPolicyRulesResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAccessPolicyRulesResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateAccessPolicyRulesResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *UpdateAccessPolicyRulesResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateAccessPolicyRulesResponse) GetData() AccessPolicyRulesGetResponseData {
	if o == nil || IsNil(o.Data) {
		var ret AccessPolicyRulesGetResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAccessPolicyRulesResponse) GetDataOk() (*AccessPolicyRulesGetResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateAccessPolicyRulesResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AccessPolicyRulesGetResponseData and assigns it to the Data field.
func (o *UpdateAccessPolicyRulesResponse) SetData(v AccessPolicyRulesGetResponseData) {
	o.Data = &v
}

func (o UpdateAccessPolicyRulesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAccessPolicyRulesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAccessPolicyRulesResponse) UnmarshalJSON(data []byte) (err error) {
	varUpdateAccessPolicyRulesResponse := _UpdateAccessPolicyRulesResponse{}

	err = json.Unmarshal(data, &varUpdateAccessPolicyRulesResponse)

	if err != nil {
		return err
	}

	*o = UpdateAccessPolicyRulesResponse(varUpdateAccessPolicyRulesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAccessPolicyRulesResponse struct {
	value *UpdateAccessPolicyRulesResponse
	isSet bool
}

func (v NullableUpdateAccessPolicyRulesResponse) Get() *UpdateAccessPolicyRulesResponse {
	return v.value
}

func (v *NullableUpdateAccessPolicyRulesResponse) Set(val *UpdateAccessPolicyRulesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAccessPolicyRulesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAccessPolicyRulesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAccessPolicyRulesResponse(val *UpdateAccessPolicyRulesResponse) *NullableUpdateAccessPolicyRulesResponse {
	return &NullableUpdateAccessPolicyRulesResponse{value: val, isSet: true}
}

func (v NullableUpdateAccessPolicyRulesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAccessPolicyRulesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


