/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the HttpsInspectionPolicyGetResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpsInspectionPolicyGetResponseData{}

// HttpsInspectionPolicyGetResponseData struct for HttpsInspectionPolicyGetResponseData
type HttpsInspectionPolicyGetResponseData struct {
	// Indicates whether the policy is controlled by Quantum or Hsase
	ControlledBy *string `json:"controlledBy,omitempty"`
	BypassRules []HttpsInspectionRule `json:"bypassRules,omitempty"`
	// Default action for traffic not matched by any explicit bypass rule (the cleanup rule). Included in the response only when the tenant has the Inspection Policy feature enabled; when the feature is off the field is omitted entirely. Defaults to \"inspect\" when the tenant has the feature enabled but hasn't configured a specific value. 
	CleanupBypassRuleDefaultAction *string `json:"cleanupBypassRuleDefaultAction,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HttpsInspectionPolicyGetResponseData HttpsInspectionPolicyGetResponseData

// NewHttpsInspectionPolicyGetResponseData instantiates a new HttpsInspectionPolicyGetResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpsInspectionPolicyGetResponseData() *HttpsInspectionPolicyGetResponseData {
	this := HttpsInspectionPolicyGetResponseData{}
	return &this
}

// NewHttpsInspectionPolicyGetResponseDataWithDefaults instantiates a new HttpsInspectionPolicyGetResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpsInspectionPolicyGetResponseDataWithDefaults() *HttpsInspectionPolicyGetResponseData {
	this := HttpsInspectionPolicyGetResponseData{}
	return &this
}

// GetControlledBy returns the ControlledBy field value if set, zero value otherwise.
func (o *HttpsInspectionPolicyGetResponseData) GetControlledBy() string {
	if o == nil || IsNil(o.ControlledBy) {
		var ret string
		return ret
	}
	return *o.ControlledBy
}

// GetControlledByOk returns a tuple with the ControlledBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpsInspectionPolicyGetResponseData) GetControlledByOk() (*string, bool) {
	if o == nil || IsNil(o.ControlledBy) {
		return nil, false
	}
	return o.ControlledBy, true
}

// HasControlledBy returns a boolean if a field has been set.
func (o *HttpsInspectionPolicyGetResponseData) HasControlledBy() bool {
	if o != nil && !IsNil(o.ControlledBy) {
		return true
	}

	return false
}

// SetControlledBy gets a reference to the given string and assigns it to the ControlledBy field.
func (o *HttpsInspectionPolicyGetResponseData) SetControlledBy(v string) {
	o.ControlledBy = &v
}

// GetBypassRules returns the BypassRules field value if set, zero value otherwise.
func (o *HttpsInspectionPolicyGetResponseData) GetBypassRules() []HttpsInspectionRule {
	if o == nil || IsNil(o.BypassRules) {
		var ret []HttpsInspectionRule
		return ret
	}
	return o.BypassRules
}

// GetBypassRulesOk returns a tuple with the BypassRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpsInspectionPolicyGetResponseData) GetBypassRulesOk() ([]HttpsInspectionRule, bool) {
	if o == nil || IsNil(o.BypassRules) {
		return nil, false
	}
	return o.BypassRules, true
}

// HasBypassRules returns a boolean if a field has been set.
func (o *HttpsInspectionPolicyGetResponseData) HasBypassRules() bool {
	if o != nil && !IsNil(o.BypassRules) {
		return true
	}

	return false
}

// SetBypassRules gets a reference to the given []HttpsInspectionRule and assigns it to the BypassRules field.
func (o *HttpsInspectionPolicyGetResponseData) SetBypassRules(v []HttpsInspectionRule) {
	o.BypassRules = v
}

// GetCleanupBypassRuleDefaultAction returns the CleanupBypassRuleDefaultAction field value if set, zero value otherwise.
func (o *HttpsInspectionPolicyGetResponseData) GetCleanupBypassRuleDefaultAction() string {
	if o == nil || IsNil(o.CleanupBypassRuleDefaultAction) {
		var ret string
		return ret
	}
	return *o.CleanupBypassRuleDefaultAction
}

// GetCleanupBypassRuleDefaultActionOk returns a tuple with the CleanupBypassRuleDefaultAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpsInspectionPolicyGetResponseData) GetCleanupBypassRuleDefaultActionOk() (*string, bool) {
	if o == nil || IsNil(o.CleanupBypassRuleDefaultAction) {
		return nil, false
	}
	return o.CleanupBypassRuleDefaultAction, true
}

// HasCleanupBypassRuleDefaultAction returns a boolean if a field has been set.
func (o *HttpsInspectionPolicyGetResponseData) HasCleanupBypassRuleDefaultAction() bool {
	if o != nil && !IsNil(o.CleanupBypassRuleDefaultAction) {
		return true
	}

	return false
}

// SetCleanupBypassRuleDefaultAction gets a reference to the given string and assigns it to the CleanupBypassRuleDefaultAction field.
func (o *HttpsInspectionPolicyGetResponseData) SetCleanupBypassRuleDefaultAction(v string) {
	o.CleanupBypassRuleDefaultAction = &v
}

func (o HttpsInspectionPolicyGetResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpsInspectionPolicyGetResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ControlledBy) {
		toSerialize["controlledBy"] = o.ControlledBy
	}
	if !IsNil(o.BypassRules) {
		toSerialize["bypassRules"] = o.BypassRules
	}
	if !IsNil(o.CleanupBypassRuleDefaultAction) {
		toSerialize["cleanupBypassRuleDefaultAction"] = o.CleanupBypassRuleDefaultAction
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HttpsInspectionPolicyGetResponseData) UnmarshalJSON(data []byte) (err error) {
	varHttpsInspectionPolicyGetResponseData := _HttpsInspectionPolicyGetResponseData{}

	err = json.Unmarshal(data, &varHttpsInspectionPolicyGetResponseData)

	if err != nil {
		return err
	}

	*o = HttpsInspectionPolicyGetResponseData(varHttpsInspectionPolicyGetResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "controlledBy")
		delete(additionalProperties, "bypassRules")
		delete(additionalProperties, "cleanupBypassRuleDefaultAction")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHttpsInspectionPolicyGetResponseData struct {
	value *HttpsInspectionPolicyGetResponseData
	isSet bool
}

func (v NullableHttpsInspectionPolicyGetResponseData) Get() *HttpsInspectionPolicyGetResponseData {
	return v.value
}

func (v *NullableHttpsInspectionPolicyGetResponseData) Set(val *HttpsInspectionPolicyGetResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpsInspectionPolicyGetResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpsInspectionPolicyGetResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpsInspectionPolicyGetResponseData(val *HttpsInspectionPolicyGetResponseData) *NullableHttpsInspectionPolicyGetResponseData {
	return &NullableHttpsInspectionPolicyGetResponseData{value: val, isSet: true}
}

func (v NullableHttpsInspectionPolicyGetResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpsInspectionPolicyGetResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


