/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SshAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SshAttributes{}

// SshAttributes SSH Application attributes
type SshAttributes struct {
	MaxConnections int32 `json:"maxConnections"`
	AdditionalProperties map[string]interface{}
}

type _SshAttributes SshAttributes

// NewSshAttributes instantiates a new SshAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSshAttributes(maxConnections int32) *SshAttributes {
	this := SshAttributes{}
	this.MaxConnections = maxConnections
	return &this
}

// NewSshAttributesWithDefaults instantiates a new SshAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSshAttributesWithDefaults() *SshAttributes {
	this := SshAttributes{}
	return &this
}

// GetMaxConnections returns the MaxConnections field value
func (o *SshAttributes) GetMaxConnections() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxConnections
}

// GetMaxConnectionsOk returns a tuple with the MaxConnections field value
// and a boolean to check if the value has been set.
func (o *SshAttributes) GetMaxConnectionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConnections, true
}

// SetMaxConnections sets field value
func (o *SshAttributes) SetMaxConnections(v int32) {
	o.MaxConnections = v
}

func (o SshAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SshAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxConnections"] = o.MaxConnections

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SshAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxConnections",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSshAttributes := _SshAttributes{}

	err = json.Unmarshal(data, &varSshAttributes)

	if err != nil {
		return err
	}

	*o = SshAttributes(varSshAttributes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "maxConnections")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSshAttributes struct {
	value *SshAttributes
	isSet bool
}

func (v NullableSshAttributes) Get() *SshAttributes {
	return v.value
}

func (v *NullableSshAttributes) Set(val *SshAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSshAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSshAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSshAttributes(val *SshAttributes) *NullableSshAttributes {
	return &NullableSshAttributes{value: val, isSet: true}
}

func (v NullableSshAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSshAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


