/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GumCustomRolesListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GumCustomRolesListResponse{}

// GumCustomRolesListResponse struct for GumCustomRolesListResponse
type GumCustomRolesListResponse struct {
	Roles []CustomRoleItem `json:"roles"`
	Total int32 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _GumCustomRolesListResponse GumCustomRolesListResponse

// NewGumCustomRolesListResponse instantiates a new GumCustomRolesListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGumCustomRolesListResponse(roles []CustomRoleItem, total int32) *GumCustomRolesListResponse {
	this := GumCustomRolesListResponse{}
	this.Roles = roles
	this.Total = total
	return &this
}

// NewGumCustomRolesListResponseWithDefaults instantiates a new GumCustomRolesListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGumCustomRolesListResponseWithDefaults() *GumCustomRolesListResponse {
	this := GumCustomRolesListResponse{}
	return &this
}

// GetRoles returns the Roles field value
func (o *GumCustomRolesListResponse) GetRoles() []CustomRoleItem {
	if o == nil {
		var ret []CustomRoleItem
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *GumCustomRolesListResponse) GetRolesOk() ([]CustomRoleItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *GumCustomRolesListResponse) SetRoles(v []CustomRoleItem) {
	o.Roles = v
}

// GetTotal returns the Total field value
func (o *GumCustomRolesListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GumCustomRolesListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GumCustomRolesListResponse) SetTotal(v int32) {
	o.Total = v
}

func (o GumCustomRolesListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GumCustomRolesListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roles"] = o.Roles
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GumCustomRolesListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roles",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGumCustomRolesListResponse := _GumCustomRolesListResponse{}

	err = json.Unmarshal(data, &varGumCustomRolesListResponse)

	if err != nil {
		return err
	}

	*o = GumCustomRolesListResponse(varGumCustomRolesListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "roles")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGumCustomRolesListResponse struct {
	value *GumCustomRolesListResponse
	isSet bool
}

func (v NullableGumCustomRolesListResponse) Get() *GumCustomRolesListResponse {
	return v.value
}

func (v *NullableGumCustomRolesListResponse) Set(val *GumCustomRolesListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGumCustomRolesListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGumCustomRolesListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGumCustomRolesListResponse(val *GumCustomRolesListResponse) *NullableGumCustomRolesListResponse {
	return &NullableGumCustomRolesListResponse{value: val, isSet: true}
}

func (v NullableGumCustomRolesListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGumCustomRolesListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


