/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// CommonCreateApplicationHost - struct for CommonCreateApplicationHost
type CommonCreateApplicationHost struct {
	FixedHost *FixedHost
	IdpHost *IdpHost
}

// FixedHostAsCommonCreateApplicationHost is a convenience function that returns FixedHost wrapped in CommonCreateApplicationHost
func FixedHostAsCommonCreateApplicationHost(v *FixedHost) CommonCreateApplicationHost {
	return CommonCreateApplicationHost{
		FixedHost: v,
	}
}

// IdpHostAsCommonCreateApplicationHost is a convenience function that returns IdpHost wrapped in CommonCreateApplicationHost
func IdpHostAsCommonCreateApplicationHost(v *IdpHost) CommonCreateApplicationHost {
	return CommonCreateApplicationHost{
		IdpHost: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CommonCreateApplicationHost) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into FixedHost
	err = json.Unmarshal(data, &dst.FixedHost)
	if err == nil {
		jsonFixedHost, _ := json.Marshal(dst.FixedHost)
		if string(jsonFixedHost) == "{}" { // empty struct
			dst.FixedHost = nil
		} else {
			match++
		}
	} else {
		dst.FixedHost = nil
	}

	// try to unmarshal data into IdpHost
	err = json.Unmarshal(data, &dst.IdpHost)
	if err == nil {
		jsonIdpHost, _ := json.Marshal(dst.IdpHost)
		if string(jsonIdpHost) == "{}" { // empty struct
			dst.IdpHost = nil
		} else {
			match++
		}
	} else {
		dst.IdpHost = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.FixedHost = nil
		dst.IdpHost = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CommonCreateApplicationHost)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
        if err != nil {
		   return fmt.Errorf("data failed to match schemas in oneOf(CommonCreateApplicationHost): %v", err)
        } else {
           return fmt.Errorf("data failed to match schemas in oneOf(CommonCreateApplicationHost)")
        }
        if err != nil {
		   return fmt.Errorf("data failed to match schemas in oneOf(CommonCreateApplicationHost): %v", err)
        } else {
           return fmt.Errorf("data failed to match schemas in oneOf(CommonCreateApplicationHost)")
        }
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CommonCreateApplicationHost) MarshalJSON() ([]byte, error) {
	if src.FixedHost != nil {
		return json.Marshal(&src.FixedHost)
	}

	if src.IdpHost != nil {
		return json.Marshal(&src.IdpHost)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CommonCreateApplicationHost) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.FixedHost != nil {
		return obj.FixedHost
	}

	if obj.IdpHost != nil {
		return obj.IdpHost
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CommonCreateApplicationHost) GetActualInstanceValue() (interface{}) {
	if obj.FixedHost != nil {
		return *obj.FixedHost
	}

	if obj.IdpHost != nil {
		return *obj.IdpHost
	}

	// all schemas are nil
	return nil
}

type NullableCommonCreateApplicationHost struct {
	value *CommonCreateApplicationHost
	isSet bool
}

func (v NullableCommonCreateApplicationHost) Get() *CommonCreateApplicationHost {
	return v.value
}

func (v *NullableCommonCreateApplicationHost) Set(val *CommonCreateApplicationHost) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonCreateApplicationHost) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonCreateApplicationHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonCreateApplicationHost(val *CommonCreateApplicationHost) *NullableCommonCreateApplicationHost {
	return &NullableCommonCreateApplicationHost{value: val, isSet: true}
}

func (v NullableCommonCreateApplicationHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonCreateApplicationHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


