/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the ApplicationAuth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationAuth{}

// ApplicationAuth Authentication settings related to the application
type ApplicationAuth struct {
	AuthEnabled *bool `json:"authEnabled,omitempty"`
	AuthUsername *string `json:"authUsername,omitempty"`
	AuthPassword *string `json:"authPassword,omitempty"`
	AuthDomain *string `json:"authDomain,omitempty" validate:"regexp=^(?!://)([a-zA-Z0-9-_]+\\.)*[a-zA-Z0-9][a-zA-Z0-9-_]*\\.[a-zA-Z0-9]{2\\,11}?$"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationAuth ApplicationAuth

// NewApplicationAuth instantiates a new ApplicationAuth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationAuth() *ApplicationAuth {
	this := ApplicationAuth{}
	return &this
}

// NewApplicationAuthWithDefaults instantiates a new ApplicationAuth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationAuthWithDefaults() *ApplicationAuth {
	this := ApplicationAuth{}
	return &this
}

// GetAuthEnabled returns the AuthEnabled field value if set, zero value otherwise.
func (o *ApplicationAuth) GetAuthEnabled() bool {
	if o == nil || IsNil(o.AuthEnabled) {
		var ret bool
		return ret
	}
	return *o.AuthEnabled
}

// GetAuthEnabledOk returns a tuple with the AuthEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationAuth) GetAuthEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.AuthEnabled) {
		return nil, false
	}
	return o.AuthEnabled, true
}

// HasAuthEnabled returns a boolean if a field has been set.
func (o *ApplicationAuth) HasAuthEnabled() bool {
	if o != nil && !IsNil(o.AuthEnabled) {
		return true
	}

	return false
}

// SetAuthEnabled gets a reference to the given bool and assigns it to the AuthEnabled field.
func (o *ApplicationAuth) SetAuthEnabled(v bool) {
	o.AuthEnabled = &v
}

// GetAuthUsername returns the AuthUsername field value if set, zero value otherwise.
func (o *ApplicationAuth) GetAuthUsername() string {
	if o == nil || IsNil(o.AuthUsername) {
		var ret string
		return ret
	}
	return *o.AuthUsername
}

// GetAuthUsernameOk returns a tuple with the AuthUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationAuth) GetAuthUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.AuthUsername) {
		return nil, false
	}
	return o.AuthUsername, true
}

// HasAuthUsername returns a boolean if a field has been set.
func (o *ApplicationAuth) HasAuthUsername() bool {
	if o != nil && !IsNil(o.AuthUsername) {
		return true
	}

	return false
}

// SetAuthUsername gets a reference to the given string and assigns it to the AuthUsername field.
func (o *ApplicationAuth) SetAuthUsername(v string) {
	o.AuthUsername = &v
}

// GetAuthPassword returns the AuthPassword field value if set, zero value otherwise.
func (o *ApplicationAuth) GetAuthPassword() string {
	if o == nil || IsNil(o.AuthPassword) {
		var ret string
		return ret
	}
	return *o.AuthPassword
}

// GetAuthPasswordOk returns a tuple with the AuthPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationAuth) GetAuthPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.AuthPassword) {
		return nil, false
	}
	return o.AuthPassword, true
}

// HasAuthPassword returns a boolean if a field has been set.
func (o *ApplicationAuth) HasAuthPassword() bool {
	if o != nil && !IsNil(o.AuthPassword) {
		return true
	}

	return false
}

// SetAuthPassword gets a reference to the given string and assigns it to the AuthPassword field.
func (o *ApplicationAuth) SetAuthPassword(v string) {
	o.AuthPassword = &v
}

// GetAuthDomain returns the AuthDomain field value if set, zero value otherwise.
func (o *ApplicationAuth) GetAuthDomain() string {
	if o == nil || IsNil(o.AuthDomain) {
		var ret string
		return ret
	}
	return *o.AuthDomain
}

// GetAuthDomainOk returns a tuple with the AuthDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationAuth) GetAuthDomainOk() (*string, bool) {
	if o == nil || IsNil(o.AuthDomain) {
		return nil, false
	}
	return o.AuthDomain, true
}

// HasAuthDomain returns a boolean if a field has been set.
func (o *ApplicationAuth) HasAuthDomain() bool {
	if o != nil && !IsNil(o.AuthDomain) {
		return true
	}

	return false
}

// SetAuthDomain gets a reference to the given string and assigns it to the AuthDomain field.
func (o *ApplicationAuth) SetAuthDomain(v string) {
	o.AuthDomain = &v
}

func (o ApplicationAuth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationAuth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthEnabled) {
		toSerialize["authEnabled"] = o.AuthEnabled
	}
	if !IsNil(o.AuthUsername) {
		toSerialize["authUsername"] = o.AuthUsername
	}
	if !IsNil(o.AuthPassword) {
		toSerialize["authPassword"] = o.AuthPassword
	}
	if !IsNil(o.AuthDomain) {
		toSerialize["authDomain"] = o.AuthDomain
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationAuth) UnmarshalJSON(data []byte) (err error) {
	varApplicationAuth := _ApplicationAuth{}

	err = json.Unmarshal(data, &varApplicationAuth)

	if err != nil {
		return err
	}

	*o = ApplicationAuth(varApplicationAuth)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authEnabled")
		delete(additionalProperties, "authUsername")
		delete(additionalProperties, "authPassword")
		delete(additionalProperties, "authDomain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationAuth struct {
	value *ApplicationAuth
	isSet bool
}

func (v NullableApplicationAuth) Get() *ApplicationAuth {
	return v.value
}

func (v *NullableApplicationAuth) Set(val *ApplicationAuth) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationAuth(val *ApplicationAuth) *NullableApplicationAuth {
	return &NullableApplicationAuth{value: val, isSet: true}
}

func (v NullableApplicationAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


