/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the IAErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IAErrorResponse{}

// IAErrorResponse struct for IAErrorResponse
type IAErrorResponse struct {
	// HTTP status code (e.g., 422, 500, 403)
	Status *int32 `json:"status,omitempty"`
	// Same as status
	Code *int32 `json:"code,omitempty"`
	// Error message or message code
	Message *string `json:"message,omitempty"`
	// Standardized error code constant
	MessageCode *string `json:"messageCode,omitempty"`
	// The marker flag
	IsP81Error *bool `json:"isP81Error,omitempty"`
	// Tenant ID (optional)
	TenantId *string `json:"tenantId,omitempty"`
	// Account ID (optional)
	AccountId *string `json:"accountId,omitempty"`
	// User ID (optional)
	UserId *string `json:"userId,omitempty"`
	Data *IAErrorResponseData `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IAErrorResponse IAErrorResponse

// NewIAErrorResponse instantiates a new IAErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIAErrorResponse() *IAErrorResponse {
	this := IAErrorResponse{}
	return &this
}

// NewIAErrorResponseWithDefaults instantiates a new IAErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIAErrorResponseWithDefaults() *IAErrorResponse {
	this := IAErrorResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *IAErrorResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *IAErrorResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *IAErrorResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *IAErrorResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *IAErrorResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *IAErrorResponse) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *IAErrorResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *IAErrorResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *IAErrorResponse) SetMessage(v string) {
	o.Message = &v
}

// GetMessageCode returns the MessageCode field value if set, zero value otherwise.
func (o *IAErrorResponse) GetMessageCode() string {
	if o == nil || IsNil(o.MessageCode) {
		var ret string
		return ret
	}
	return *o.MessageCode
}

// GetMessageCodeOk returns a tuple with the MessageCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetMessageCodeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageCode) {
		return nil, false
	}
	return o.MessageCode, true
}

// HasMessageCode returns a boolean if a field has been set.
func (o *IAErrorResponse) HasMessageCode() bool {
	if o != nil && !IsNil(o.MessageCode) {
		return true
	}

	return false
}

// SetMessageCode gets a reference to the given string and assigns it to the MessageCode field.
func (o *IAErrorResponse) SetMessageCode(v string) {
	o.MessageCode = &v
}

// GetIsP81Error returns the IsP81Error field value if set, zero value otherwise.
func (o *IAErrorResponse) GetIsP81Error() bool {
	if o == nil || IsNil(o.IsP81Error) {
		var ret bool
		return ret
	}
	return *o.IsP81Error
}

// GetIsP81ErrorOk returns a tuple with the IsP81Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetIsP81ErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsP81Error) {
		return nil, false
	}
	return o.IsP81Error, true
}

// HasIsP81Error returns a boolean if a field has been set.
func (o *IAErrorResponse) HasIsP81Error() bool {
	if o != nil && !IsNil(o.IsP81Error) {
		return true
	}

	return false
}

// SetIsP81Error gets a reference to the given bool and assigns it to the IsP81Error field.
func (o *IAErrorResponse) SetIsP81Error(v bool) {
	o.IsP81Error = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *IAErrorResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *IAErrorResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *IAErrorResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *IAErrorResponse) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *IAErrorResponse) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *IAErrorResponse) SetAccountId(v string) {
	o.AccountId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *IAErrorResponse) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *IAErrorResponse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *IAErrorResponse) SetUserId(v string) {
	o.UserId = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *IAErrorResponse) GetData() IAErrorResponseData {
	if o == nil || IsNil(o.Data) {
		var ret IAErrorResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IAErrorResponse) GetDataOk() (*IAErrorResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *IAErrorResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given IAErrorResponseData and assigns it to the Data field.
func (o *IAErrorResponse) SetData(v IAErrorResponseData) {
	o.Data = &v
}

func (o IAErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IAErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.MessageCode) {
		toSerialize["messageCode"] = o.MessageCode
	}
	if !IsNil(o.IsP81Error) {
		toSerialize["isP81Error"] = o.IsP81Error
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IAErrorResponse) UnmarshalJSON(data []byte) (err error) {
	varIAErrorResponse := _IAErrorResponse{}

	err = json.Unmarshal(data, &varIAErrorResponse)

	if err != nil {
		return err
	}

	*o = IAErrorResponse(varIAErrorResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "code")
		delete(additionalProperties, "message")
		delete(additionalProperties, "messageCode")
		delete(additionalProperties, "isP81Error")
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "accountId")
		delete(additionalProperties, "userId")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIAErrorResponse struct {
	value *IAErrorResponse
	isSet bool
}

func (v NullableIAErrorResponse) Get() *IAErrorResponse {
	return v.value
}

func (v *NullableIAErrorResponse) Set(val *IAErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIAErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIAErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIAErrorResponse(val *IAErrorResponse) *NullableIAErrorResponse {
	return &NullableIAErrorResponse{value: val, isSet: true}
}

func (v NullableIAErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIAErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


