/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GumInternalErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GumInternalErrorResponse{}

// GumInternalErrorResponse struct for GumInternalErrorResponse
type GumInternalErrorResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _GumInternalErrorResponse GumInternalErrorResponse

// NewGumInternalErrorResponse instantiates a new GumInternalErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGumInternalErrorResponse(success bool, message string) *GumInternalErrorResponse {
	this := GumInternalErrorResponse{}
	this.Success = success
	this.Message = message
	return &this
}

// NewGumInternalErrorResponseWithDefaults instantiates a new GumInternalErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGumInternalErrorResponseWithDefaults() *GumInternalErrorResponse {
	this := GumInternalErrorResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *GumInternalErrorResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *GumInternalErrorResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *GumInternalErrorResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *GumInternalErrorResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GumInternalErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GumInternalErrorResponse) SetMessage(v string) {
	o.Message = v
}

func (o GumInternalErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GumInternalErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GumInternalErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGumInternalErrorResponse := _GumInternalErrorResponse{}

	err = json.Unmarshal(data, &varGumInternalErrorResponse)

	if err != nil {
		return err
	}

	*o = GumInternalErrorResponse(varGumInternalErrorResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGumInternalErrorResponse struct {
	value *GumInternalErrorResponse
	isSet bool
}

func (v NullableGumInternalErrorResponse) Get() *GumInternalErrorResponse {
	return v.value
}

func (v *NullableGumInternalErrorResponse) Set(val *GumInternalErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGumInternalErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGumInternalErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGumInternalErrorResponse(val *GumInternalErrorResponse) *NullableGumInternalErrorResponse {
	return &NullableGumInternalErrorResponse{value: val, isSet: true}
}

func (v NullableGumInternalErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGumInternalErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


