/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User struct for User
type User struct {
	InitialsColor *string `json:"initialsColor,omitempty"`
	InvitationAttempts *int32 `json:"invitationAttempts,omitempty"`
	// Invitation token.
	InvitationToken *string `json:"invitationToken,omitempty"`
	// Reference ID to `Role`.
	Role *string `json:"role,omitempty"`
	// Friendly names of the roles assigned to the user (built-in and custom).
	Roles []string `json:"roles,omitempty"`
	IdProviderGroups []string `json:"idProviderGroups,omitempty"`
	IdProviders *IdProviderMap `json:"idProviders,omitempty"`
	// Invitation message sent to the user.
	InviteMessage *string `json:"inviteMessage,omitempty"`
	// Indicates that the user has been deleted.
	Terminated bool `json:"terminated"`
	// User email.
	Email string `json:"email"`
	// Whether the user verified his email.
	EmailVerified bool `json:"emailVerified"`
	// User initials.
	Initials string `json:"initials"`
	// User role name.
	RoleName string `json:"roleName"`
	// User last name.
	LastName string `json:"lastName"`
	// User first name.
	FirstName string `json:"firstName"`
	// User name.
	Username string `json:"username"`
	AdditionalProperties map[string]interface{}
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(terminated bool, email string, emailVerified bool, initials string, roleName string, lastName string, firstName string, username string) *User {
	this := User{}
	this.Terminated = terminated
	this.Email = email
	this.EmailVerified = emailVerified
	this.Initials = initials
	this.RoleName = roleName
	this.LastName = lastName
	this.FirstName = firstName
	this.Username = username
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetInitialsColor returns the InitialsColor field value if set, zero value otherwise.
func (o *User) GetInitialsColor() string {
	if o == nil || IsNil(o.InitialsColor) {
		var ret string
		return ret
	}
	return *o.InitialsColor
}

// GetInitialsColorOk returns a tuple with the InitialsColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetInitialsColorOk() (*string, bool) {
	if o == nil || IsNil(o.InitialsColor) {
		return nil, false
	}
	return o.InitialsColor, true
}

// HasInitialsColor returns a boolean if a field has been set.
func (o *User) HasInitialsColor() bool {
	if o != nil && !IsNil(o.InitialsColor) {
		return true
	}

	return false
}

// SetInitialsColor gets a reference to the given string and assigns it to the InitialsColor field.
func (o *User) SetInitialsColor(v string) {
	o.InitialsColor = &v
}

// GetInvitationAttempts returns the InvitationAttempts field value if set, zero value otherwise.
func (o *User) GetInvitationAttempts() int32 {
	if o == nil || IsNil(o.InvitationAttempts) {
		var ret int32
		return ret
	}
	return *o.InvitationAttempts
}

// GetInvitationAttemptsOk returns a tuple with the InvitationAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetInvitationAttemptsOk() (*int32, bool) {
	if o == nil || IsNil(o.InvitationAttempts) {
		return nil, false
	}
	return o.InvitationAttempts, true
}

// HasInvitationAttempts returns a boolean if a field has been set.
func (o *User) HasInvitationAttempts() bool {
	if o != nil && !IsNil(o.InvitationAttempts) {
		return true
	}

	return false
}

// SetInvitationAttempts gets a reference to the given int32 and assigns it to the InvitationAttempts field.
func (o *User) SetInvitationAttempts(v int32) {
	o.InvitationAttempts = &v
}

// GetInvitationToken returns the InvitationToken field value if set, zero value otherwise.
func (o *User) GetInvitationToken() string {
	if o == nil || IsNil(o.InvitationToken) {
		var ret string
		return ret
	}
	return *o.InvitationToken
}

// GetInvitationTokenOk returns a tuple with the InvitationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetInvitationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.InvitationToken) {
		return nil, false
	}
	return o.InvitationToken, true
}

// HasInvitationToken returns a boolean if a field has been set.
func (o *User) HasInvitationToken() bool {
	if o != nil && !IsNil(o.InvitationToken) {
		return true
	}

	return false
}

// SetInvitationToken gets a reference to the given string and assigns it to the InvitationToken field.
func (o *User) SetInvitationToken(v string) {
	o.InvitationToken = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *User) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *User) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *User) SetRole(v string) {
	o.Role = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *User) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *User) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *User) SetRoles(v []string) {
	o.Roles = v
}

// GetIdProviderGroups returns the IdProviderGroups field value if set, zero value otherwise.
func (o *User) GetIdProviderGroups() []string {
	if o == nil || IsNil(o.IdProviderGroups) {
		var ret []string
		return ret
	}
	return o.IdProviderGroups
}

// GetIdProviderGroupsOk returns a tuple with the IdProviderGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIdProviderGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.IdProviderGroups) {
		return nil, false
	}
	return o.IdProviderGroups, true
}

// HasIdProviderGroups returns a boolean if a field has been set.
func (o *User) HasIdProviderGroups() bool {
	if o != nil && !IsNil(o.IdProviderGroups) {
		return true
	}

	return false
}

// SetIdProviderGroups gets a reference to the given []string and assigns it to the IdProviderGroups field.
func (o *User) SetIdProviderGroups(v []string) {
	o.IdProviderGroups = v
}

// GetIdProviders returns the IdProviders field value if set, zero value otherwise.
func (o *User) GetIdProviders() IdProviderMap {
	if o == nil || IsNil(o.IdProviders) {
		var ret IdProviderMap
		return ret
	}
	return *o.IdProviders
}

// GetIdProvidersOk returns a tuple with the IdProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIdProvidersOk() (*IdProviderMap, bool) {
	if o == nil || IsNil(o.IdProviders) {
		return nil, false
	}
	return o.IdProviders, true
}

// HasIdProviders returns a boolean if a field has been set.
func (o *User) HasIdProviders() bool {
	if o != nil && !IsNil(o.IdProviders) {
		return true
	}

	return false
}

// SetIdProviders gets a reference to the given IdProviderMap and assigns it to the IdProviders field.
func (o *User) SetIdProviders(v IdProviderMap) {
	o.IdProviders = &v
}

// GetInviteMessage returns the InviteMessage field value if set, zero value otherwise.
func (o *User) GetInviteMessage() string {
	if o == nil || IsNil(o.InviteMessage) {
		var ret string
		return ret
	}
	return *o.InviteMessage
}

// GetInviteMessageOk returns a tuple with the InviteMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetInviteMessageOk() (*string, bool) {
	if o == nil || IsNil(o.InviteMessage) {
		return nil, false
	}
	return o.InviteMessage, true
}

// HasInviteMessage returns a boolean if a field has been set.
func (o *User) HasInviteMessage() bool {
	if o != nil && !IsNil(o.InviteMessage) {
		return true
	}

	return false
}

// SetInviteMessage gets a reference to the given string and assigns it to the InviteMessage field.
func (o *User) SetInviteMessage(v string) {
	o.InviteMessage = &v
}

// GetTerminated returns the Terminated field value
func (o *User) GetTerminated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Terminated
}

// GetTerminatedOk returns a tuple with the Terminated field value
// and a boolean to check if the value has been set.
func (o *User) GetTerminatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Terminated, true
}

// SetTerminated sets field value
func (o *User) SetTerminated(v bool) {
	o.Terminated = v
}

// GetEmail returns the Email field value
func (o *User) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *User) SetEmail(v string) {
	o.Email = v
}

// GetEmailVerified returns the EmailVerified field value
func (o *User) GetEmailVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EmailVerified
}

// GetEmailVerifiedOk returns a tuple with the EmailVerified field value
// and a boolean to check if the value has been set.
func (o *User) GetEmailVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailVerified, true
}

// SetEmailVerified sets field value
func (o *User) SetEmailVerified(v bool) {
	o.EmailVerified = v
}

// GetInitials returns the Initials field value
func (o *User) GetInitials() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Initials
}

// GetInitialsOk returns a tuple with the Initials field value
// and a boolean to check if the value has been set.
func (o *User) GetInitialsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Initials, true
}

// SetInitials sets field value
func (o *User) SetInitials(v string) {
	o.Initials = v
}

// GetRoleName returns the RoleName field value
func (o *User) GetRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *User) GetRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleName, true
}

// SetRoleName sets field value
func (o *User) SetRoleName(v string) {
	o.RoleName = v
}

// GetLastName returns the LastName field value
func (o *User) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *User) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *User) SetLastName(v string) {
	o.LastName = v
}

// GetFirstName returns the FirstName field value
func (o *User) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *User) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *User) SetFirstName(v string) {
	o.FirstName = v
}

// GetUsername returns the Username field value
func (o *User) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *User) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *User) SetUsername(v string) {
	o.Username = v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InitialsColor) {
		toSerialize["initialsColor"] = o.InitialsColor
	}
	if !IsNil(o.InvitationAttempts) {
		toSerialize["invitationAttempts"] = o.InvitationAttempts
	}
	if !IsNil(o.InvitationToken) {
		toSerialize["invitationToken"] = o.InvitationToken
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	if !IsNil(o.IdProviderGroups) {
		toSerialize["idProviderGroups"] = o.IdProviderGroups
	}
	if !IsNil(o.IdProviders) {
		toSerialize["idProviders"] = o.IdProviders
	}
	if !IsNil(o.InviteMessage) {
		toSerialize["inviteMessage"] = o.InviteMessage
	}
	toSerialize["terminated"] = o.Terminated
	toSerialize["email"] = o.Email
	toSerialize["emailVerified"] = o.EmailVerified
	toSerialize["initials"] = o.Initials
	toSerialize["roleName"] = o.RoleName
	toSerialize["lastName"] = o.LastName
	toSerialize["firstName"] = o.FirstName
	toSerialize["username"] = o.Username

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"terminated",
		"email",
		"emailVerified",
		"initials",
		"roleName",
		"lastName",
		"firstName",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUser := _User{}

	err = json.Unmarshal(data, &varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "initialsColor")
		delete(additionalProperties, "invitationAttempts")
		delete(additionalProperties, "invitationToken")
		delete(additionalProperties, "role")
		delete(additionalProperties, "roles")
		delete(additionalProperties, "idProviderGroups")
		delete(additionalProperties, "idProviders")
		delete(additionalProperties, "inviteMessage")
		delete(additionalProperties, "terminated")
		delete(additionalProperties, "email")
		delete(additionalProperties, "emailVerified")
		delete(additionalProperties, "initials")
		delete(additionalProperties, "roleName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "username")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


