/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GranularFirewallPolicyRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GranularFirewallPolicyRule{}

// GranularFirewallPolicyRule Firewall policy rule for the granular /networks/{networkId}/firewall-policy endpoint, where per-rule logging (logEnabled) is required.
type GranularFirewallPolicyRule struct {
	// Unique policy rule ID.
	Id *string `json:"id,omitempty" validate:"regexp=^[a-zA-Z0-9]+$"`
	// Name of the policy rule.
	Name string `json:"name"`
	// Enables or disables the rule on the firewall. When set to true, the rule is active; when false, the rule is inactive.
	Enabled bool `json:"enabled"`
	// Determines the rule action. When set to true, traffic is allowed; when false, traffic is blocked.
	Allowed bool `json:"allowed"`
	Sources SourcesAndDestinations `json:"sources"`
	Destinations SourcesAndDestinations `json:"destinations"`
	// List of service object IDs.
	Services []string `json:"services,omitempty"`
	// whether logging is enabled for this rule.
	LogEnabled bool `json:"logEnabled"`
	AdditionalProperties map[string]interface{}
}

type _GranularFirewallPolicyRule GranularFirewallPolicyRule

// NewGranularFirewallPolicyRule instantiates a new GranularFirewallPolicyRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGranularFirewallPolicyRule(name string, enabled bool, allowed bool, sources SourcesAndDestinations, destinations SourcesAndDestinations, logEnabled bool) *GranularFirewallPolicyRule {
	this := GranularFirewallPolicyRule{}
	this.Name = name
	this.Enabled = enabled
	this.Allowed = allowed
	this.Sources = sources
	this.Destinations = destinations
	this.LogEnabled = logEnabled
	return &this
}

// NewGranularFirewallPolicyRuleWithDefaults instantiates a new GranularFirewallPolicyRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGranularFirewallPolicyRuleWithDefaults() *GranularFirewallPolicyRule {
	this := GranularFirewallPolicyRule{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GranularFirewallPolicyRule) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GranularFirewallPolicyRule) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GranularFirewallPolicyRule) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *GranularFirewallPolicyRule) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GranularFirewallPolicyRule) SetName(v string) {
	o.Name = v
}

// GetEnabled returns the Enabled field value
func (o *GranularFirewallPolicyRule) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *GranularFirewallPolicyRule) SetEnabled(v bool) {
	o.Enabled = v
}

// GetAllowed returns the Allowed field value
func (o *GranularFirewallPolicyRule) GetAllowed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Allowed
}

// GetAllowedOk returns a tuple with the Allowed field value
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetAllowedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Allowed, true
}

// SetAllowed sets field value
func (o *GranularFirewallPolicyRule) SetAllowed(v bool) {
	o.Allowed = v
}

// GetSources returns the Sources field value
func (o *GranularFirewallPolicyRule) GetSources() SourcesAndDestinations {
	if o == nil {
		var ret SourcesAndDestinations
		return ret
	}

	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetSourcesOk() (*SourcesAndDestinations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sources, true
}

// SetSources sets field value
func (o *GranularFirewallPolicyRule) SetSources(v SourcesAndDestinations) {
	o.Sources = v
}

// GetDestinations returns the Destinations field value
func (o *GranularFirewallPolicyRule) GetDestinations() SourcesAndDestinations {
	if o == nil {
		var ret SourcesAndDestinations
		return ret
	}

	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetDestinationsOk() (*SourcesAndDestinations, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destinations, true
}

// SetDestinations sets field value
func (o *GranularFirewallPolicyRule) SetDestinations(v SourcesAndDestinations) {
	o.Destinations = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *GranularFirewallPolicyRule) GetServices() []string {
	if o == nil || IsNil(o.Services) {
		var ret []string
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *GranularFirewallPolicyRule) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []string and assigns it to the Services field.
func (o *GranularFirewallPolicyRule) SetServices(v []string) {
	o.Services = v
}

// GetLogEnabled returns the LogEnabled field value
func (o *GranularFirewallPolicyRule) GetLogEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogEnabled
}

// GetLogEnabledOk returns a tuple with the LogEnabled field value
// and a boolean to check if the value has been set.
func (o *GranularFirewallPolicyRule) GetLogEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogEnabled, true
}

// SetLogEnabled sets field value
func (o *GranularFirewallPolicyRule) SetLogEnabled(v bool) {
	o.LogEnabled = v
}

func (o GranularFirewallPolicyRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GranularFirewallPolicyRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["enabled"] = o.Enabled
	toSerialize["allowed"] = o.Allowed
	toSerialize["sources"] = o.Sources
	toSerialize["destinations"] = o.Destinations
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	toSerialize["logEnabled"] = o.LogEnabled

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GranularFirewallPolicyRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"enabled",
		"allowed",
		"sources",
		"destinations",
		"logEnabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGranularFirewallPolicyRule := _GranularFirewallPolicyRule{}

	err = json.Unmarshal(data, &varGranularFirewallPolicyRule)

	if err != nil {
		return err
	}

	*o = GranularFirewallPolicyRule(varGranularFirewallPolicyRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "allowed")
		delete(additionalProperties, "sources")
		delete(additionalProperties, "destinations")
		delete(additionalProperties, "services")
		delete(additionalProperties, "logEnabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGranularFirewallPolicyRule struct {
	value *GranularFirewallPolicyRule
	isSet bool
}

func (v NullableGranularFirewallPolicyRule) Get() *GranularFirewallPolicyRule {
	return v.value
}

func (v *NullableGranularFirewallPolicyRule) Set(val *GranularFirewallPolicyRule) {
	v.value = val
	v.isSet = true
}

func (v NullableGranularFirewallPolicyRule) IsSet() bool {
	return v.isSet
}

func (v *NullableGranularFirewallPolicyRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGranularFirewallPolicyRule(val *GranularFirewallPolicyRule) *NullableGranularFirewallPolicyRule {
	return &NullableGranularFirewallPolicyRule{value: val, isSet: true}
}

func (v NullableGranularFirewallPolicyRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGranularFirewallPolicyRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


