/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the CustomDnsAttributesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomDnsAttributesResponse{}

// CustomDnsAttributesResponse Private DNS attributes as returned for standard (CoreV3) networks.
type CustomDnsAttributesResponse struct {
	// Private DNS servers
	Servers []CustomDnsServer `json:"servers,omitempty"`
	// DNS search domains for domain resolution
	SearchDomains []string `json:"searchDomains,omitempty"`
	DnsPolicy *DnsPolicyResponse `json:"dnsPolicy,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomDnsAttributesResponse CustomDnsAttributesResponse

// NewCustomDnsAttributesResponse instantiates a new CustomDnsAttributesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomDnsAttributesResponse() *CustomDnsAttributesResponse {
	this := CustomDnsAttributesResponse{}
	return &this
}

// NewCustomDnsAttributesResponseWithDefaults instantiates a new CustomDnsAttributesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomDnsAttributesResponseWithDefaults() *CustomDnsAttributesResponse {
	this := CustomDnsAttributesResponse{}
	return &this
}

// GetServers returns the Servers field value if set, zero value otherwise.
func (o *CustomDnsAttributesResponse) GetServers() []CustomDnsServer {
	if o == nil || IsNil(o.Servers) {
		var ret []CustomDnsServer
		return ret
	}
	return o.Servers
}

// GetServersOk returns a tuple with the Servers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomDnsAttributesResponse) GetServersOk() ([]CustomDnsServer, bool) {
	if o == nil || IsNil(o.Servers) {
		return nil, false
	}
	return o.Servers, true
}

// HasServers returns a boolean if a field has been set.
func (o *CustomDnsAttributesResponse) HasServers() bool {
	if o != nil && !IsNil(o.Servers) {
		return true
	}

	return false
}

// SetServers gets a reference to the given []CustomDnsServer and assigns it to the Servers field.
func (o *CustomDnsAttributesResponse) SetServers(v []CustomDnsServer) {
	o.Servers = v
}

// GetSearchDomains returns the SearchDomains field value if set, zero value otherwise.
func (o *CustomDnsAttributesResponse) GetSearchDomains() []string {
	if o == nil || IsNil(o.SearchDomains) {
		var ret []string
		return ret
	}
	return o.SearchDomains
}

// GetSearchDomainsOk returns a tuple with the SearchDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomDnsAttributesResponse) GetSearchDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.SearchDomains) {
		return nil, false
	}
	return o.SearchDomains, true
}

// HasSearchDomains returns a boolean if a field has been set.
func (o *CustomDnsAttributesResponse) HasSearchDomains() bool {
	if o != nil && !IsNil(o.SearchDomains) {
		return true
	}

	return false
}

// SetSearchDomains gets a reference to the given []string and assigns it to the SearchDomains field.
func (o *CustomDnsAttributesResponse) SetSearchDomains(v []string) {
	o.SearchDomains = v
}

// GetDnsPolicy returns the DnsPolicy field value if set, zero value otherwise.
func (o *CustomDnsAttributesResponse) GetDnsPolicy() DnsPolicyResponse {
	if o == nil || IsNil(o.DnsPolicy) {
		var ret DnsPolicyResponse
		return ret
	}
	return *o.DnsPolicy
}

// GetDnsPolicyOk returns a tuple with the DnsPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomDnsAttributesResponse) GetDnsPolicyOk() (*DnsPolicyResponse, bool) {
	if o == nil || IsNil(o.DnsPolicy) {
		return nil, false
	}
	return o.DnsPolicy, true
}

// HasDnsPolicy returns a boolean if a field has been set.
func (o *CustomDnsAttributesResponse) HasDnsPolicy() bool {
	if o != nil && !IsNil(o.DnsPolicy) {
		return true
	}

	return false
}

// SetDnsPolicy gets a reference to the given DnsPolicyResponse and assigns it to the DnsPolicy field.
func (o *CustomDnsAttributesResponse) SetDnsPolicy(v DnsPolicyResponse) {
	o.DnsPolicy = &v
}

func (o CustomDnsAttributesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomDnsAttributesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Servers) {
		toSerialize["servers"] = o.Servers
	}
	if !IsNil(o.SearchDomains) {
		toSerialize["searchDomains"] = o.SearchDomains
	}
	if !IsNil(o.DnsPolicy) {
		toSerialize["dnsPolicy"] = o.DnsPolicy
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomDnsAttributesResponse) UnmarshalJSON(data []byte) (err error) {
	varCustomDnsAttributesResponse := _CustomDnsAttributesResponse{}

	err = json.Unmarshal(data, &varCustomDnsAttributesResponse)

	if err != nil {
		return err
	}

	*o = CustomDnsAttributesResponse(varCustomDnsAttributesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "servers")
		delete(additionalProperties, "searchDomains")
		delete(additionalProperties, "dnsPolicy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomDnsAttributesResponse struct {
	value *CustomDnsAttributesResponse
	isSet bool
}

func (v NullableCustomDnsAttributesResponse) Get() *CustomDnsAttributesResponse {
	return v.value
}

func (v *NullableCustomDnsAttributesResponse) Set(val *CustomDnsAttributesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomDnsAttributesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomDnsAttributesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomDnsAttributesResponse(val *CustomDnsAttributesResponse) *NullableCustomDnsAttributesResponse {
	return &NullableCustomDnsAttributesResponse{value: val, isSet: true}
}

func (v NullableCustomDnsAttributesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomDnsAttributesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


