/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthorizeResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizeResponseData{}

// AuthorizeResponseData struct for AuthorizeResponseData
type AuthorizeResponseData struct {
	// Token type
	TokenType string `json:"tokenType"`
	// JWT access token
	AccessToken string `json:"accessToken"`
	// Unix timestamp when access token expires
	AccessTokenExpire int32 `json:"accessTokenExpire"`
	// Tenant identifier
	TenantId string `json:"tenantId"`
	// Encrypted session identifier
	SessionId string `json:"sessionId"`
	AdditionalProperties map[string]interface{}
}

type _AuthorizeResponseData AuthorizeResponseData

// NewAuthorizeResponseData instantiates a new AuthorizeResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizeResponseData(tokenType string, accessToken string, accessTokenExpire int32, tenantId string, sessionId string) *AuthorizeResponseData {
	this := AuthorizeResponseData{}
	this.TokenType = tokenType
	this.AccessToken = accessToken
	this.AccessTokenExpire = accessTokenExpire
	this.TenantId = tenantId
	this.SessionId = sessionId
	return &this
}

// NewAuthorizeResponseDataWithDefaults instantiates a new AuthorizeResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizeResponseDataWithDefaults() *AuthorizeResponseData {
	this := AuthorizeResponseData{}
	return &this
}

// GetTokenType returns the TokenType field value
func (o *AuthorizeResponseData) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *AuthorizeResponseData) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *AuthorizeResponseData) SetTokenType(v string) {
	o.TokenType = v
}

// GetAccessToken returns the AccessToken field value
func (o *AuthorizeResponseData) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *AuthorizeResponseData) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *AuthorizeResponseData) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetAccessTokenExpire returns the AccessTokenExpire field value
func (o *AuthorizeResponseData) GetAccessTokenExpire() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccessTokenExpire
}

// GetAccessTokenExpireOk returns a tuple with the AccessTokenExpire field value
// and a boolean to check if the value has been set.
func (o *AuthorizeResponseData) GetAccessTokenExpireOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessTokenExpire, true
}

// SetAccessTokenExpire sets field value
func (o *AuthorizeResponseData) SetAccessTokenExpire(v int32) {
	o.AccessTokenExpire = v
}

// GetTenantId returns the TenantId field value
func (o *AuthorizeResponseData) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *AuthorizeResponseData) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *AuthorizeResponseData) SetTenantId(v string) {
	o.TenantId = v
}

// GetSessionId returns the SessionId field value
func (o *AuthorizeResponseData) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *AuthorizeResponseData) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *AuthorizeResponseData) SetSessionId(v string) {
	o.SessionId = v
}

func (o AuthorizeResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizeResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tokenType"] = o.TokenType
	toSerialize["accessToken"] = o.AccessToken
	toSerialize["accessTokenExpire"] = o.AccessTokenExpire
	toSerialize["tenantId"] = o.TenantId
	toSerialize["sessionId"] = o.SessionId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthorizeResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tokenType",
		"accessToken",
		"accessTokenExpire",
		"tenantId",
		"sessionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthorizeResponseData := _AuthorizeResponseData{}

	err = json.Unmarshal(data, &varAuthorizeResponseData)

	if err != nil {
		return err
	}

	*o = AuthorizeResponseData(varAuthorizeResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tokenType")
		delete(additionalProperties, "accessToken")
		delete(additionalProperties, "accessTokenExpire")
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "sessionId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthorizeResponseData struct {
	value *AuthorizeResponseData
	isSet bool
}

func (v NullableAuthorizeResponseData) Get() *AuthorizeResponseData {
	return v.value
}

func (v *NullableAuthorizeResponseData) Set(val *AuthorizeResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizeResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizeResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizeResponseData(val *AuthorizeResponseData) *NullableAuthorizeResponseData {
	return &NullableAuthorizeResponseData{value: val, isSet: true}
}

func (v NullableAuthorizeResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizeResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


