/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the GetAccessPolicy500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccessPolicy500Response{}

// GetAccessPolicy500Response struct for GetAccessPolicy500Response
type GetAccessPolicy500Response struct {
	Message *string `json:"message,omitempty"`
	MessageCode *string `json:"messageCode,omitempty"`
	Status *int32 `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetAccessPolicy500Response GetAccessPolicy500Response

// NewGetAccessPolicy500Response instantiates a new GetAccessPolicy500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccessPolicy500Response() *GetAccessPolicy500Response {
	this := GetAccessPolicy500Response{}
	return &this
}

// NewGetAccessPolicy500ResponseWithDefaults instantiates a new GetAccessPolicy500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccessPolicy500ResponseWithDefaults() *GetAccessPolicy500Response {
	this := GetAccessPolicy500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetAccessPolicy500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPolicy500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetAccessPolicy500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetAccessPolicy500Response) SetMessage(v string) {
	o.Message = &v
}

// GetMessageCode returns the MessageCode field value if set, zero value otherwise.
func (o *GetAccessPolicy500Response) GetMessageCode() string {
	if o == nil || IsNil(o.MessageCode) {
		var ret string
		return ret
	}
	return *o.MessageCode
}

// GetMessageCodeOk returns a tuple with the MessageCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPolicy500Response) GetMessageCodeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageCode) {
		return nil, false
	}
	return o.MessageCode, true
}

// HasMessageCode returns a boolean if a field has been set.
func (o *GetAccessPolicy500Response) HasMessageCode() bool {
	if o != nil && !IsNil(o.MessageCode) {
		return true
	}

	return false
}

// SetMessageCode gets a reference to the given string and assigns it to the MessageCode field.
func (o *GetAccessPolicy500Response) SetMessageCode(v string) {
	o.MessageCode = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetAccessPolicy500Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccessPolicy500Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetAccessPolicy500Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *GetAccessPolicy500Response) SetStatus(v int32) {
	o.Status = &v
}

func (o GetAccessPolicy500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccessPolicy500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.MessageCode) {
		toSerialize["messageCode"] = o.MessageCode
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetAccessPolicy500Response) UnmarshalJSON(data []byte) (err error) {
	varGetAccessPolicy500Response := _GetAccessPolicy500Response{}

	err = json.Unmarshal(data, &varGetAccessPolicy500Response)

	if err != nil {
		return err
	}

	*o = GetAccessPolicy500Response(varGetAccessPolicy500Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "messageCode")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetAccessPolicy500Response struct {
	value *GetAccessPolicy500Response
	isSet bool
}

func (v NullableGetAccessPolicy500Response) Get() *GetAccessPolicy500Response {
	return v.value
}

func (v *NullableGetAccessPolicy500Response) Set(val *GetAccessPolicy500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccessPolicy500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccessPolicy500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccessPolicy500Response(val *GetAccessPolicy500Response) *NullableGetAccessPolicy500Response {
	return &NullableGetAccessPolicy500Response{value: val, isSet: true}
}

func (v NullableGetAccessPolicy500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccessPolicy500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


