/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CategoryEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryEntry{}

// CategoryEntry struct for CategoryEntry
type CategoryEntry struct {
	CategoryId string `json:"categoryId"`
	Access string `json:"access"`
	AdditionalProperties map[string]interface{}
}

type _CategoryEntry CategoryEntry

// NewCategoryEntry instantiates a new CategoryEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryEntry(categoryId string, access string) *CategoryEntry {
	this := CategoryEntry{}
	this.CategoryId = categoryId
	this.Access = access
	return &this
}

// NewCategoryEntryWithDefaults instantiates a new CategoryEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryEntryWithDefaults() *CategoryEntry {
	this := CategoryEntry{}
	return &this
}

// GetCategoryId returns the CategoryId field value
func (o *CategoryEntry) GetCategoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value
// and a boolean to check if the value has been set.
func (o *CategoryEntry) GetCategoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CategoryId, true
}

// SetCategoryId sets field value
func (o *CategoryEntry) SetCategoryId(v string) {
	o.CategoryId = v
}

// GetAccess returns the Access field value
func (o *CategoryEntry) GetAccess() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Access
}

// GetAccessOk returns a tuple with the Access field value
// and a boolean to check if the value has been set.
func (o *CategoryEntry) GetAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Access, true
}

// SetAccess sets field value
func (o *CategoryEntry) SetAccess(v string) {
	o.Access = v
}

func (o CategoryEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["categoryId"] = o.CategoryId
	toSerialize["access"] = o.Access

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CategoryEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"categoryId",
		"access",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryEntry := _CategoryEntry{}

	err = json.Unmarshal(data, &varCategoryEntry)

	if err != nil {
		return err
	}

	*o = CategoryEntry(varCategoryEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "categoryId")
		delete(additionalProperties, "access")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCategoryEntry struct {
	value *CategoryEntry
	isSet bool
}

func (v NullableCategoryEntry) Get() *CategoryEntry {
	return v.value
}

func (v *NullableCategoryEntry) Set(val *CategoryEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryEntry(val *CategoryEntry) *NullableCategoryEntry {
	return &NullableCategoryEntry{value: val, isSet: true}
}

func (v NullableCategoryEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


