/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the StaticTunnelCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StaticTunnelCreate{}

// StaticTunnelCreate struct for StaticTunnelCreate
type StaticTunnelCreate struct {
	// Authentication type for tunnel (psk for pre-shared key, cert for certificate)
	AuthType string `json:"authType"`
	// Pre-shared key for tunnel authentication (8-64 characters). Required when authType is psk.
	Passphrase *string `json:"passphrase,omitempty"`
	// Customer root certificate authority. Required when authType is cert.
	CustomerRootCA *string `json:"customerRootCA,omitempty"`
	// Target region ID
	RegionID string `json:"regionID"`
	// Name of the static tunnel
	TunnelName string `json:"tunnelName"`
	// Harmony Sase gateway subnets
	P81GatewaySubnets []string `json:"p81GatewaySubnets"`
	// Remote gateway subnets
	RemoteGatewaySubnets []string `json:"remoteGatewaySubnets"`
	// IKE version for key exchange
	KeyExchange string `json:"keyExchange"`
	IkeLifeTime string `json:"ikeLifeTime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2\\,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	Lifetime string `json:"lifetime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2\\,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	DpdDelay string `json:"dpdDelay" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	DpdTimeout string `json:"dpdTimeout" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	Phase1 IPSecPhaseConfigV23 `json:"phase1"`
	Phase2 IPSecPhaseConfigV23 `json:"phase2"`
	// Remote gateway public IP address
	RemotePublicIP string `json:"remotePublicIP"`
	// Remote gateway ID
	RemoteID string `json:"remoteID"`
	// Optional tunnel description
	Description *string `json:"description,omitempty"`
	Features NetworkFeaturesCreate `json:"features"`
	RoutingType RoutingType `json:"routingType"`
	// Expected peak throughput of the tunnel communication in Mbps. Typical connection will be of 1000Mbps.
	PeakBandwidthMbps *int32 `json:"peakBandwidthMbps,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StaticTunnelCreate StaticTunnelCreate

// NewStaticTunnelCreate instantiates a new StaticTunnelCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticTunnelCreate(authType string, regionID string, tunnelName string, p81GatewaySubnets []string, remoteGatewaySubnets []string, keyExchange string, ikeLifeTime string, lifetime string, dpdDelay string, dpdTimeout string, phase1 IPSecPhaseConfigV23, phase2 IPSecPhaseConfigV23, remotePublicIP string, remoteID string, features NetworkFeaturesCreate, routingType RoutingType) *StaticTunnelCreate {
	this := StaticTunnelCreate{}
	this.AuthType = authType
	this.RegionID = regionID
	this.TunnelName = tunnelName
	this.P81GatewaySubnets = p81GatewaySubnets
	this.RemoteGatewaySubnets = remoteGatewaySubnets
	this.KeyExchange = keyExchange
	this.IkeLifeTime = ikeLifeTime
	this.Lifetime = lifetime
	this.DpdDelay = dpdDelay
	this.DpdTimeout = dpdTimeout
	this.Phase1 = phase1
	this.Phase2 = phase2
	this.RemotePublicIP = remotePublicIP
	this.RemoteID = remoteID
	this.Features = features
	this.RoutingType = routingType
	var peakBandwidthMbps int32 = 1000
	this.PeakBandwidthMbps = &peakBandwidthMbps
	return &this
}

// NewStaticTunnelCreateWithDefaults instantiates a new StaticTunnelCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticTunnelCreateWithDefaults() *StaticTunnelCreate {
	this := StaticTunnelCreate{}
	var keyExchange string = "ikev2"
	this.KeyExchange = keyExchange
	var routingType RoutingType = ROUTINGTYPE_ROUTE
	this.RoutingType = routingType
	var peakBandwidthMbps int32 = 1000
	this.PeakBandwidthMbps = &peakBandwidthMbps
	return &this
}

// GetAuthType returns the AuthType field value
func (o *StaticTunnelCreate) GetAuthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *StaticTunnelCreate) SetAuthType(v string) {
	o.AuthType = v
}

// GetPassphrase returns the Passphrase field value if set, zero value otherwise.
func (o *StaticTunnelCreate) GetPassphrase() string {
	if o == nil || IsNil(o.Passphrase) {
		var ret string
		return ret
	}
	return *o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetPassphraseOk() (*string, bool) {
	if o == nil || IsNil(o.Passphrase) {
		return nil, false
	}
	return o.Passphrase, true
}

// HasPassphrase returns a boolean if a field has been set.
func (o *StaticTunnelCreate) HasPassphrase() bool {
	if o != nil && !IsNil(o.Passphrase) {
		return true
	}

	return false
}

// SetPassphrase gets a reference to the given string and assigns it to the Passphrase field.
func (o *StaticTunnelCreate) SetPassphrase(v string) {
	o.Passphrase = &v
}

// GetCustomerRootCA returns the CustomerRootCA field value if set, zero value otherwise.
func (o *StaticTunnelCreate) GetCustomerRootCA() string {
	if o == nil || IsNil(o.CustomerRootCA) {
		var ret string
		return ret
	}
	return *o.CustomerRootCA
}

// GetCustomerRootCAOk returns a tuple with the CustomerRootCA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetCustomerRootCAOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerRootCA) {
		return nil, false
	}
	return o.CustomerRootCA, true
}

// HasCustomerRootCA returns a boolean if a field has been set.
func (o *StaticTunnelCreate) HasCustomerRootCA() bool {
	if o != nil && !IsNil(o.CustomerRootCA) {
		return true
	}

	return false
}

// SetCustomerRootCA gets a reference to the given string and assigns it to the CustomerRootCA field.
func (o *StaticTunnelCreate) SetCustomerRootCA(v string) {
	o.CustomerRootCA = &v
}

// GetRegionID returns the RegionID field value
func (o *StaticTunnelCreate) GetRegionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionID
}

// GetRegionIDOk returns a tuple with the RegionID field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetRegionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionID, true
}

// SetRegionID sets field value
func (o *StaticTunnelCreate) SetRegionID(v string) {
	o.RegionID = v
}

// GetTunnelName returns the TunnelName field value
func (o *StaticTunnelCreate) GetTunnelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetTunnelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelName, true
}

// SetTunnelName sets field value
func (o *StaticTunnelCreate) SetTunnelName(v string) {
	o.TunnelName = v
}

// GetP81GatewaySubnets returns the P81GatewaySubnets field value
func (o *StaticTunnelCreate) GetP81GatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.P81GatewaySubnets
}

// GetP81GatewaySubnetsOk returns a tuple with the P81GatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetP81GatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.P81GatewaySubnets, true
}

// SetP81GatewaySubnets sets field value
func (o *StaticTunnelCreate) SetP81GatewaySubnets(v []string) {
	o.P81GatewaySubnets = v
}

// GetRemoteGatewaySubnets returns the RemoteGatewaySubnets field value
func (o *StaticTunnelCreate) GetRemoteGatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemoteGatewaySubnets
}

// GetRemoteGatewaySubnetsOk returns a tuple with the RemoteGatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetRemoteGatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGatewaySubnets, true
}

// SetRemoteGatewaySubnets sets field value
func (o *StaticTunnelCreate) SetRemoteGatewaySubnets(v []string) {
	o.RemoteGatewaySubnets = v
}

// GetKeyExchange returns the KeyExchange field value
func (o *StaticTunnelCreate) GetKeyExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetKeyExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyExchange, true
}

// SetKeyExchange sets field value
func (o *StaticTunnelCreate) SetKeyExchange(v string) {
	o.KeyExchange = v
}

// GetIkeLifeTime returns the IkeLifeTime field value
func (o *StaticTunnelCreate) GetIkeLifeTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IkeLifeTime
}

// GetIkeLifeTimeOk returns a tuple with the IkeLifeTime field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetIkeLifeTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IkeLifeTime, true
}

// SetIkeLifeTime sets field value
func (o *StaticTunnelCreate) SetIkeLifeTime(v string) {
	o.IkeLifeTime = v
}

// GetLifetime returns the Lifetime field value
func (o *StaticTunnelCreate) GetLifetime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lifetime
}

// GetLifetimeOk returns a tuple with the Lifetime field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetLifetimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lifetime, true
}

// SetLifetime sets field value
func (o *StaticTunnelCreate) SetLifetime(v string) {
	o.Lifetime = v
}

// GetDpdDelay returns the DpdDelay field value
func (o *StaticTunnelCreate) GetDpdDelay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdDelay
}

// GetDpdDelayOk returns a tuple with the DpdDelay field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetDpdDelayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdDelay, true
}

// SetDpdDelay sets field value
func (o *StaticTunnelCreate) SetDpdDelay(v string) {
	o.DpdDelay = v
}

// GetDpdTimeout returns the DpdTimeout field value
func (o *StaticTunnelCreate) GetDpdTimeout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdTimeout
}

// GetDpdTimeoutOk returns a tuple with the DpdTimeout field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetDpdTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdTimeout, true
}

// SetDpdTimeout sets field value
func (o *StaticTunnelCreate) SetDpdTimeout(v string) {
	o.DpdTimeout = v
}

// GetPhase1 returns the Phase1 field value
func (o *StaticTunnelCreate) GetPhase1() IPSecPhaseConfigV23 {
	if o == nil {
		var ret IPSecPhaseConfigV23
		return ret
	}

	return o.Phase1
}

// GetPhase1Ok returns a tuple with the Phase1 field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetPhase1Ok() (*IPSecPhaseConfigV23, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase1, true
}

// SetPhase1 sets field value
func (o *StaticTunnelCreate) SetPhase1(v IPSecPhaseConfigV23) {
	o.Phase1 = v
}

// GetPhase2 returns the Phase2 field value
func (o *StaticTunnelCreate) GetPhase2() IPSecPhaseConfigV23 {
	if o == nil {
		var ret IPSecPhaseConfigV23
		return ret
	}

	return o.Phase2
}

// GetPhase2Ok returns a tuple with the Phase2 field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetPhase2Ok() (*IPSecPhaseConfigV23, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase2, true
}

// SetPhase2 sets field value
func (o *StaticTunnelCreate) SetPhase2(v IPSecPhaseConfigV23) {
	o.Phase2 = v
}

// GetRemotePublicIP returns the RemotePublicIP field value
func (o *StaticTunnelCreate) GetRemotePublicIP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemotePublicIP
}

// GetRemotePublicIPOk returns a tuple with the RemotePublicIP field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetRemotePublicIPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemotePublicIP, true
}

// SetRemotePublicIP sets field value
func (o *StaticTunnelCreate) SetRemotePublicIP(v string) {
	o.RemotePublicIP = v
}

// GetRemoteID returns the RemoteID field value
func (o *StaticTunnelCreate) GetRemoteID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteID
}

// GetRemoteIDOk returns a tuple with the RemoteID field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetRemoteIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteID, true
}

// SetRemoteID sets field value
func (o *StaticTunnelCreate) SetRemoteID(v string) {
	o.RemoteID = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StaticTunnelCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StaticTunnelCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StaticTunnelCreate) SetDescription(v string) {
	o.Description = &v
}

// GetFeatures returns the Features field value
func (o *StaticTunnelCreate) GetFeatures() NetworkFeaturesCreate {
	if o == nil {
		var ret NetworkFeaturesCreate
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetFeaturesOk() (*NetworkFeaturesCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Features, true
}

// SetFeatures sets field value
func (o *StaticTunnelCreate) SetFeatures(v NetworkFeaturesCreate) {
	o.Features = v
}

// GetRoutingType returns the RoutingType field value
func (o *StaticTunnelCreate) GetRoutingType() RoutingType {
	if o == nil {
		var ret RoutingType
		return ret
	}

	return o.RoutingType
}

// GetRoutingTypeOk returns a tuple with the RoutingType field value
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetRoutingTypeOk() (*RoutingType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingType, true
}

// SetRoutingType sets field value
func (o *StaticTunnelCreate) SetRoutingType(v RoutingType) {
	o.RoutingType = v
}

// GetPeakBandwidthMbps returns the PeakBandwidthMbps field value if set, zero value otherwise.
func (o *StaticTunnelCreate) GetPeakBandwidthMbps() int32 {
	if o == nil || IsNil(o.PeakBandwidthMbps) {
		var ret int32
		return ret
	}
	return *o.PeakBandwidthMbps
}

// GetPeakBandwidthMbpsOk returns a tuple with the PeakBandwidthMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticTunnelCreate) GetPeakBandwidthMbpsOk() (*int32, bool) {
	if o == nil || IsNil(o.PeakBandwidthMbps) {
		return nil, false
	}
	return o.PeakBandwidthMbps, true
}

// HasPeakBandwidthMbps returns a boolean if a field has been set.
func (o *StaticTunnelCreate) HasPeakBandwidthMbps() bool {
	if o != nil && !IsNil(o.PeakBandwidthMbps) {
		return true
	}

	return false
}

// SetPeakBandwidthMbps gets a reference to the given int32 and assigns it to the PeakBandwidthMbps field.
func (o *StaticTunnelCreate) SetPeakBandwidthMbps(v int32) {
	o.PeakBandwidthMbps = &v
}

func (o StaticTunnelCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StaticTunnelCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authType"] = o.AuthType
	if !IsNil(o.Passphrase) {
		toSerialize["passphrase"] = o.Passphrase
	}
	if !IsNil(o.CustomerRootCA) {
		toSerialize["customerRootCA"] = o.CustomerRootCA
	}
	toSerialize["regionID"] = o.RegionID
	toSerialize["tunnelName"] = o.TunnelName
	toSerialize["p81GatewaySubnets"] = o.P81GatewaySubnets
	toSerialize["remoteGatewaySubnets"] = o.RemoteGatewaySubnets
	toSerialize["keyExchange"] = o.KeyExchange
	toSerialize["ikeLifeTime"] = o.IkeLifeTime
	toSerialize["lifetime"] = o.Lifetime
	toSerialize["dpdDelay"] = o.DpdDelay
	toSerialize["dpdTimeout"] = o.DpdTimeout
	toSerialize["phase1"] = o.Phase1
	toSerialize["phase2"] = o.Phase2
	toSerialize["remotePublicIP"] = o.RemotePublicIP
	toSerialize["remoteID"] = o.RemoteID
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["features"] = o.Features
	toSerialize["routingType"] = o.RoutingType
	if !IsNil(o.PeakBandwidthMbps) {
		toSerialize["peakBandwidthMbps"] = o.PeakBandwidthMbps
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StaticTunnelCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authType",
		"regionID",
		"tunnelName",
		"p81GatewaySubnets",
		"remoteGatewaySubnets",
		"keyExchange",
		"ikeLifeTime",
		"lifetime",
		"dpdDelay",
		"dpdTimeout",
		"phase1",
		"phase2",
		"remotePublicIP",
		"remoteID",
		"features",
		"routingType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStaticTunnelCreate := _StaticTunnelCreate{}

	err = json.Unmarshal(data, &varStaticTunnelCreate)

	if err != nil {
		return err
	}

	*o = StaticTunnelCreate(varStaticTunnelCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authType")
		delete(additionalProperties, "passphrase")
		delete(additionalProperties, "customerRootCA")
		delete(additionalProperties, "regionID")
		delete(additionalProperties, "tunnelName")
		delete(additionalProperties, "p81GatewaySubnets")
		delete(additionalProperties, "remoteGatewaySubnets")
		delete(additionalProperties, "keyExchange")
		delete(additionalProperties, "ikeLifeTime")
		delete(additionalProperties, "lifetime")
		delete(additionalProperties, "dpdDelay")
		delete(additionalProperties, "dpdTimeout")
		delete(additionalProperties, "phase1")
		delete(additionalProperties, "phase2")
		delete(additionalProperties, "remotePublicIP")
		delete(additionalProperties, "remoteID")
		delete(additionalProperties, "description")
		delete(additionalProperties, "features")
		delete(additionalProperties, "routingType")
		delete(additionalProperties, "peakBandwidthMbps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStaticTunnelCreate struct {
	value *StaticTunnelCreate
	isSet bool
}

func (v NullableStaticTunnelCreate) Get() *StaticTunnelCreate {
	return v.value
}

func (v *NullableStaticTunnelCreate) Set(val *StaticTunnelCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticTunnelCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticTunnelCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticTunnelCreate(val *StaticTunnelCreate) *NullableStaticTunnelCreate {
	return &NullableStaticTunnelCreate{value: val, isSet: true}
}

func (v NullableStaticTunnelCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticTunnelCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


