/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the WebCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebCategory{}

// WebCategory struct for WebCategory
type WebCategory struct {
	// Web Category ID
	Id string `json:"id"`
	// Web Category name
	Name string `json:"name"`
	// Web Category code identifiers
	Codes []string `json:"codes"`
	AdditionalProperties map[string]interface{}
}

type _WebCategory WebCategory

// NewWebCategory instantiates a new WebCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebCategory(id string, name string, codes []string) *WebCategory {
	this := WebCategory{}
	this.Id = id
	this.Name = name
	this.Codes = codes
	return &this
}

// NewWebCategoryWithDefaults instantiates a new WebCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebCategoryWithDefaults() *WebCategory {
	this := WebCategory{}
	return &this
}

// GetId returns the Id field value
func (o *WebCategory) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebCategory) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebCategory) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *WebCategory) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebCategory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebCategory) SetName(v string) {
	o.Name = v
}

// GetCodes returns the Codes field value
func (o *WebCategory) GetCodes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Codes
}

// GetCodesOk returns a tuple with the Codes field value
// and a boolean to check if the value has been set.
func (o *WebCategory) GetCodesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Codes, true
}

// SetCodes sets field value
func (o *WebCategory) SetCodes(v []string) {
	o.Codes = v
}

func (o WebCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["codes"] = o.Codes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebCategory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebCategory := _WebCategory{}

	err = json.Unmarshal(data, &varWebCategory)

	if err != nil {
		return err
	}

	*o = WebCategory(varWebCategory)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "codes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebCategory struct {
	value *WebCategory
	isSet bool
}

func (v NullableWebCategory) Get() *WebCategory {
	return v.value
}

func (v *NullableWebCategory) Set(val *WebCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableWebCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableWebCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebCategory(val *WebCategory) *NullableWebCategory {
	return &NullableWebCategory{value: val, isSet: true}
}

func (v NullableWebCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


