/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the BasicApplicationAllOfGroupsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasicApplicationAllOfGroupsInner{}

// BasicApplicationAllOfGroupsInner Application groups
type BasicApplicationAllOfGroupsInner struct {
	// Unique Group ID
	Id *string `json:"id,omitempty"`
	// Group's name
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BasicApplicationAllOfGroupsInner BasicApplicationAllOfGroupsInner

// NewBasicApplicationAllOfGroupsInner instantiates a new BasicApplicationAllOfGroupsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicApplicationAllOfGroupsInner() *BasicApplicationAllOfGroupsInner {
	this := BasicApplicationAllOfGroupsInner{}
	return &this
}

// NewBasicApplicationAllOfGroupsInnerWithDefaults instantiates a new BasicApplicationAllOfGroupsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicApplicationAllOfGroupsInnerWithDefaults() *BasicApplicationAllOfGroupsInner {
	this := BasicApplicationAllOfGroupsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BasicApplicationAllOfGroupsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicApplicationAllOfGroupsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BasicApplicationAllOfGroupsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BasicApplicationAllOfGroupsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BasicApplicationAllOfGroupsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicApplicationAllOfGroupsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BasicApplicationAllOfGroupsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BasicApplicationAllOfGroupsInner) SetName(v string) {
	o.Name = &v
}

func (o BasicApplicationAllOfGroupsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasicApplicationAllOfGroupsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BasicApplicationAllOfGroupsInner) UnmarshalJSON(data []byte) (err error) {
	varBasicApplicationAllOfGroupsInner := _BasicApplicationAllOfGroupsInner{}

	err = json.Unmarshal(data, &varBasicApplicationAllOfGroupsInner)

	if err != nil {
		return err
	}

	*o = BasicApplicationAllOfGroupsInner(varBasicApplicationAllOfGroupsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBasicApplicationAllOfGroupsInner struct {
	value *BasicApplicationAllOfGroupsInner
	isSet bool
}

func (v NullableBasicApplicationAllOfGroupsInner) Get() *BasicApplicationAllOfGroupsInner {
	return v.value
}

func (v *NullableBasicApplicationAllOfGroupsInner) Set(val *BasicApplicationAllOfGroupsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicApplicationAllOfGroupsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicApplicationAllOfGroupsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicApplicationAllOfGroupsInner(val *BasicApplicationAllOfGroupsInner) *NullableBasicApplicationAllOfGroupsInner {
	return &NullableBasicApplicationAllOfGroupsInner{value: val, isSet: true}
}

func (v NullableBasicApplicationAllOfGroupsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicApplicationAllOfGroupsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


