/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomDnsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomDnsResponse{}

// CustomDnsResponse Private DNS configuration as returned for standard (CoreV3) networks and regions.
type CustomDnsResponse struct {
	// Indicates whether private DNS is enabled
	Enabled bool `json:"enabled"`
	Attributes *CustomDnsAttributesResponse `json:"attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomDnsResponse CustomDnsResponse

// NewCustomDnsResponse instantiates a new CustomDnsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomDnsResponse(enabled bool) *CustomDnsResponse {
	this := CustomDnsResponse{}
	this.Enabled = enabled
	return &this
}

// NewCustomDnsResponseWithDefaults instantiates a new CustomDnsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomDnsResponseWithDefaults() *CustomDnsResponse {
	this := CustomDnsResponse{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *CustomDnsResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CustomDnsResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CustomDnsResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *CustomDnsResponse) GetAttributes() CustomDnsAttributesResponse {
	if o == nil || IsNil(o.Attributes) {
		var ret CustomDnsAttributesResponse
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomDnsResponse) GetAttributesOk() (*CustomDnsAttributesResponse, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *CustomDnsResponse) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given CustomDnsAttributesResponse and assigns it to the Attributes field.
func (o *CustomDnsResponse) SetAttributes(v CustomDnsAttributesResponse) {
	o.Attributes = &v
}

func (o CustomDnsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomDnsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomDnsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomDnsResponse := _CustomDnsResponse{}

	err = json.Unmarshal(data, &varCustomDnsResponse)

	if err != nil {
		return err
	}

	*o = CustomDnsResponse(varCustomDnsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomDnsResponse struct {
	value *CustomDnsResponse
	isSet bool
}

func (v NullableCustomDnsResponse) Get() *CustomDnsResponse {
	return v.value
}

func (v *NullableCustomDnsResponse) Set(val *CustomDnsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomDnsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomDnsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomDnsResponse(val *CustomDnsResponse) *NullableCustomDnsResponse {
	return &NullableCustomDnsResponse{value: val, isSet: true}
}

func (v NullableCustomDnsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomDnsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


