/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the WebCreateApplication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebCreateApplication{}

// WebCreateApplication struct for WebCreateApplication
type WebCreateApplication struct {
	// Application name
	Name string `json:"name" validate:"regexp=^[^~\x60()!#$%^&*+=[]\\';\\,/{}|\":<>?№@]+$"`
	// Application type
	Type string `json:"type"`
	// Application network ID. To get the ID use endpoint '/networks' with [network:read] permission.
	Network string `json:"network" validate:"regexp=^[a-zA-Z0-9]+$"`
	Host CommonCreateApplicationHost `json:"host"`
	Port CommonCreateApplicationPort `json:"port"`
	Users []string `json:"users"`
	Groups []string `json:"groups"`
	// Application specific headers. Keys must not contain . and $
	Headers map[string]interface{} `json:"headers"`
	AdditionalProperties map[string]interface{}
}

type _WebCreateApplication WebCreateApplication

// NewWebCreateApplication instantiates a new WebCreateApplication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebCreateApplication(name string, type_ string, network string, host CommonCreateApplicationHost, port CommonCreateApplicationPort, users []string, groups []string, headers map[string]interface{}) *WebCreateApplication {
	this := WebCreateApplication{}
	this.Name = name
	this.Type = type_
	this.Network = network
	this.Host = host
	this.Port = port
	this.Users = users
	this.Groups = groups
	this.Headers = headers
	return &this
}

// NewWebCreateApplicationWithDefaults instantiates a new WebCreateApplication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebCreateApplicationWithDefaults() *WebCreateApplication {
	this := WebCreateApplication{}
	return &this
}

// GetName returns the Name field value
func (o *WebCreateApplication) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebCreateApplication) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *WebCreateApplication) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WebCreateApplication) SetType(v string) {
	o.Type = v
}

// GetNetwork returns the Network field value
func (o *WebCreateApplication) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *WebCreateApplication) SetNetwork(v string) {
	o.Network = v
}

// GetHost returns the Host field value
func (o *WebCreateApplication) GetHost() CommonCreateApplicationHost {
	if o == nil {
		var ret CommonCreateApplicationHost
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetHostOk() (*CommonCreateApplicationHost, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *WebCreateApplication) SetHost(v CommonCreateApplicationHost) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *WebCreateApplication) GetPort() CommonCreateApplicationPort {
	if o == nil {
		var ret CommonCreateApplicationPort
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetPortOk() (*CommonCreateApplicationPort, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *WebCreateApplication) SetPort(v CommonCreateApplicationPort) {
	o.Port = v
}

// GetUsers returns the Users field value
func (o *WebCreateApplication) GetUsers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetUsersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *WebCreateApplication) SetUsers(v []string) {
	o.Users = v
}

// GetGroups returns the Groups field value
func (o *WebCreateApplication) GetGroups() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetGroupsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *WebCreateApplication) SetGroups(v []string) {
	o.Groups = v
}

// GetHeaders returns the Headers field value
func (o *WebCreateApplication) GetHeaders() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value
// and a boolean to check if the value has been set.
func (o *WebCreateApplication) GetHeadersOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Headers, true
}

// SetHeaders sets field value
func (o *WebCreateApplication) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

func (o WebCreateApplication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebCreateApplication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["network"] = o.Network
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	toSerialize["users"] = o.Users
	toSerialize["groups"] = o.Groups
	toSerialize["headers"] = o.Headers

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebCreateApplication) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"network",
		"host",
		"port",
		"users",
		"groups",
		"headers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebCreateApplication := _WebCreateApplication{}

	err = json.Unmarshal(data, &varWebCreateApplication)

	if err != nil {
		return err
	}

	*o = WebCreateApplication(varWebCreateApplication)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "network")
		delete(additionalProperties, "host")
		delete(additionalProperties, "port")
		delete(additionalProperties, "users")
		delete(additionalProperties, "groups")
		delete(additionalProperties, "headers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebCreateApplication struct {
	value *WebCreateApplication
	isSet bool
}

func (v NullableWebCreateApplication) Get() *WebCreateApplication {
	return v.value
}

func (v *NullableWebCreateApplication) Set(val *WebCreateApplication) {
	v.value = val
	v.isSet = true
}

func (v NullableWebCreateApplication) IsSet() bool {
	return v.isSet
}

func (v *NullableWebCreateApplication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebCreateApplication(val *WebCreateApplication) *NullableWebCreateApplication {
	return &NullableWebCreateApplication{value: val, isSet: true}
}

func (v NullableWebCreateApplication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebCreateApplication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


