/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the AccessPolicyRulesGetResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessPolicyRulesGetResponseData{}

// AccessPolicyRulesGetResponseData struct for AccessPolicyRulesGetResponseData
type AccessPolicyRulesGetResponseData struct {
	WebRules []AccessPolicyRule `json:"webRules,omitempty"`
	// Indicates whether the policy is controlled by Quantum or Hsase
	ControlledBy *string `json:"controlledBy,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccessPolicyRulesGetResponseData AccessPolicyRulesGetResponseData

// NewAccessPolicyRulesGetResponseData instantiates a new AccessPolicyRulesGetResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessPolicyRulesGetResponseData() *AccessPolicyRulesGetResponseData {
	this := AccessPolicyRulesGetResponseData{}
	return &this
}

// NewAccessPolicyRulesGetResponseDataWithDefaults instantiates a new AccessPolicyRulesGetResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessPolicyRulesGetResponseDataWithDefaults() *AccessPolicyRulesGetResponseData {
	this := AccessPolicyRulesGetResponseData{}
	return &this
}

// GetWebRules returns the WebRules field value if set, zero value otherwise.
func (o *AccessPolicyRulesGetResponseData) GetWebRules() []AccessPolicyRule {
	if o == nil || IsNil(o.WebRules) {
		var ret []AccessPolicyRule
		return ret
	}
	return o.WebRules
}

// GetWebRulesOk returns a tuple with the WebRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessPolicyRulesGetResponseData) GetWebRulesOk() ([]AccessPolicyRule, bool) {
	if o == nil || IsNil(o.WebRules) {
		return nil, false
	}
	return o.WebRules, true
}

// HasWebRules returns a boolean if a field has been set.
func (o *AccessPolicyRulesGetResponseData) HasWebRules() bool {
	if o != nil && !IsNil(o.WebRules) {
		return true
	}

	return false
}

// SetWebRules gets a reference to the given []AccessPolicyRule and assigns it to the WebRules field.
func (o *AccessPolicyRulesGetResponseData) SetWebRules(v []AccessPolicyRule) {
	o.WebRules = v
}

// GetControlledBy returns the ControlledBy field value if set, zero value otherwise.
func (o *AccessPolicyRulesGetResponseData) GetControlledBy() string {
	if o == nil || IsNil(o.ControlledBy) {
		var ret string
		return ret
	}
	return *o.ControlledBy
}

// GetControlledByOk returns a tuple with the ControlledBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessPolicyRulesGetResponseData) GetControlledByOk() (*string, bool) {
	if o == nil || IsNil(o.ControlledBy) {
		return nil, false
	}
	return o.ControlledBy, true
}

// HasControlledBy returns a boolean if a field has been set.
func (o *AccessPolicyRulesGetResponseData) HasControlledBy() bool {
	if o != nil && !IsNil(o.ControlledBy) {
		return true
	}

	return false
}

// SetControlledBy gets a reference to the given string and assigns it to the ControlledBy field.
func (o *AccessPolicyRulesGetResponseData) SetControlledBy(v string) {
	o.ControlledBy = &v
}

func (o AccessPolicyRulesGetResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessPolicyRulesGetResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WebRules) {
		toSerialize["webRules"] = o.WebRules
	}
	if !IsNil(o.ControlledBy) {
		toSerialize["controlledBy"] = o.ControlledBy
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccessPolicyRulesGetResponseData) UnmarshalJSON(data []byte) (err error) {
	varAccessPolicyRulesGetResponseData := _AccessPolicyRulesGetResponseData{}

	err = json.Unmarshal(data, &varAccessPolicyRulesGetResponseData)

	if err != nil {
		return err
	}

	*o = AccessPolicyRulesGetResponseData(varAccessPolicyRulesGetResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "webRules")
		delete(additionalProperties, "controlledBy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccessPolicyRulesGetResponseData struct {
	value *AccessPolicyRulesGetResponseData
	isSet bool
}

func (v NullableAccessPolicyRulesGetResponseData) Get() *AccessPolicyRulesGetResponseData {
	return v.value
}

func (v *NullableAccessPolicyRulesGetResponseData) Set(val *AccessPolicyRulesGetResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessPolicyRulesGetResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessPolicyRulesGetResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessPolicyRulesGetResponseData(val *AccessPolicyRulesGetResponseData) *NullableAccessPolicyRulesGetResponseData {
	return &NullableAccessPolicyRulesGetResponseData{value: val, isSet: true}
}

func (v NullableAccessPolicyRulesGetResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessPolicyRulesGetResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


