/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GumCustomRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GumCustomRoleResponse{}

// GumCustomRoleResponse struct for GumCustomRoleResponse
type GumCustomRoleResponse struct {
	Role CustomRoleItem `json:"role"`
	AdditionalProperties map[string]interface{}
}

type _GumCustomRoleResponse GumCustomRoleResponse

// NewGumCustomRoleResponse instantiates a new GumCustomRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGumCustomRoleResponse(role CustomRoleItem) *GumCustomRoleResponse {
	this := GumCustomRoleResponse{}
	this.Role = role
	return &this
}

// NewGumCustomRoleResponseWithDefaults instantiates a new GumCustomRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGumCustomRoleResponseWithDefaults() *GumCustomRoleResponse {
	this := GumCustomRoleResponse{}
	return &this
}

// GetRole returns the Role field value
func (o *GumCustomRoleResponse) GetRole() CustomRoleItem {
	if o == nil {
		var ret CustomRoleItem
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GumCustomRoleResponse) GetRoleOk() (*CustomRoleItem, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GumCustomRoleResponse) SetRole(v CustomRoleItem) {
	o.Role = v
}

func (o GumCustomRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GumCustomRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GumCustomRoleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGumCustomRoleResponse := _GumCustomRoleResponse{}

	err = json.Unmarshal(data, &varGumCustomRoleResponse)

	if err != nil {
		return err
	}

	*o = GumCustomRoleResponse(varGumCustomRoleResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "role")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGumCustomRoleResponse struct {
	value *GumCustomRoleResponse
	isSet bool
}

func (v NullableGumCustomRoleResponse) Get() *GumCustomRoleResponse {
	return v.value
}

func (v *NullableGumCustomRoleResponse) Set(val *GumCustomRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGumCustomRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGumCustomRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGumCustomRoleResponse(val *GumCustomRoleResponse) *NullableGumCustomRoleResponse {
	return &NullableGumCustomRoleResponse{value: val, isSet: true}
}

func (v NullableGumCustomRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGumCustomRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


