/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UpsertHttpsInspectionPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertHttpsInspectionPolicy{}

// UpsertHttpsInspectionPolicy struct for UpsertHttpsInspectionPolicy
type UpsertHttpsInspectionPolicy struct {
	BypassRules []HttpsInspectionRule `json:"bypassRules"`
	// Optional. Default action for traffic not matched by any explicit bypass rule (the cleanup rule). Per-tenant setting — scope-agnostic. Accepted only when the tenant has the Inspection Policy feature enabled; otherwise the request is rejected with 422 VALIDATION_CLEANUP_ACTION_NOT_ALLOWED. Semantics: 'inspect' (default) applies full HTTPS inspection to unmatched traffic; 'inspectNoDecrypt' inspects without decrypting on the agent path; 'bypass' causes unmatched traffic to skip HTTPS inspection entirely. 
	CleanupBypassRuleDefaultAction *string `json:"cleanupBypassRuleDefaultAction,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpsertHttpsInspectionPolicy UpsertHttpsInspectionPolicy

// NewUpsertHttpsInspectionPolicy instantiates a new UpsertHttpsInspectionPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertHttpsInspectionPolicy(bypassRules []HttpsInspectionRule) *UpsertHttpsInspectionPolicy {
	this := UpsertHttpsInspectionPolicy{}
	this.BypassRules = bypassRules
	return &this
}

// NewUpsertHttpsInspectionPolicyWithDefaults instantiates a new UpsertHttpsInspectionPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertHttpsInspectionPolicyWithDefaults() *UpsertHttpsInspectionPolicy {
	this := UpsertHttpsInspectionPolicy{}
	return &this
}

// GetBypassRules returns the BypassRules field value
func (o *UpsertHttpsInspectionPolicy) GetBypassRules() []HttpsInspectionRule {
	if o == nil {
		var ret []HttpsInspectionRule
		return ret
	}

	return o.BypassRules
}

// GetBypassRulesOk returns a tuple with the BypassRules field value
// and a boolean to check if the value has been set.
func (o *UpsertHttpsInspectionPolicy) GetBypassRulesOk() ([]HttpsInspectionRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.BypassRules, true
}

// SetBypassRules sets field value
func (o *UpsertHttpsInspectionPolicy) SetBypassRules(v []HttpsInspectionRule) {
	o.BypassRules = v
}

// GetCleanupBypassRuleDefaultAction returns the CleanupBypassRuleDefaultAction field value if set, zero value otherwise.
func (o *UpsertHttpsInspectionPolicy) GetCleanupBypassRuleDefaultAction() string {
	if o == nil || IsNil(o.CleanupBypassRuleDefaultAction) {
		var ret string
		return ret
	}
	return *o.CleanupBypassRuleDefaultAction
}

// GetCleanupBypassRuleDefaultActionOk returns a tuple with the CleanupBypassRuleDefaultAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertHttpsInspectionPolicy) GetCleanupBypassRuleDefaultActionOk() (*string, bool) {
	if o == nil || IsNil(o.CleanupBypassRuleDefaultAction) {
		return nil, false
	}
	return o.CleanupBypassRuleDefaultAction, true
}

// HasCleanupBypassRuleDefaultAction returns a boolean if a field has been set.
func (o *UpsertHttpsInspectionPolicy) HasCleanupBypassRuleDefaultAction() bool {
	if o != nil && !IsNil(o.CleanupBypassRuleDefaultAction) {
		return true
	}

	return false
}

// SetCleanupBypassRuleDefaultAction gets a reference to the given string and assigns it to the CleanupBypassRuleDefaultAction field.
func (o *UpsertHttpsInspectionPolicy) SetCleanupBypassRuleDefaultAction(v string) {
	o.CleanupBypassRuleDefaultAction = &v
}

func (o UpsertHttpsInspectionPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertHttpsInspectionPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bypassRules"] = o.BypassRules
	if !IsNil(o.CleanupBypassRuleDefaultAction) {
		toSerialize["cleanupBypassRuleDefaultAction"] = o.CleanupBypassRuleDefaultAction
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpsertHttpsInspectionPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bypassRules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsertHttpsInspectionPolicy := _UpsertHttpsInspectionPolicy{}

	err = json.Unmarshal(data, &varUpsertHttpsInspectionPolicy)

	if err != nil {
		return err
	}

	*o = UpsertHttpsInspectionPolicy(varUpsertHttpsInspectionPolicy)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bypassRules")
		delete(additionalProperties, "cleanupBypassRuleDefaultAction")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpsertHttpsInspectionPolicy struct {
	value *UpsertHttpsInspectionPolicy
	isSet bool
}

func (v NullableUpsertHttpsInspectionPolicy) Get() *UpsertHttpsInspectionPolicy {
	return v.value
}

func (v *NullableUpsertHttpsInspectionPolicy) Set(val *UpsertHttpsInspectionPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertHttpsInspectionPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertHttpsInspectionPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertHttpsInspectionPolicy(val *UpsertHttpsInspectionPolicy) *NullableUpsertHttpsInspectionPolicy {
	return &NullableUpsertHttpsInspectionPolicy{value: val, isSet: true}
}

func (v NullableUpsertHttpsInspectionPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertHttpsInspectionPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


