/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomDnsServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomDnsServer{}

// CustomDnsServer Private DNS server entry.
type CustomDnsServer struct {
	// IP address of the DNS server
	Address string `json:"address"`
	// Indicates if DNS-over-TLS is used
	IsTLS bool `json:"isTLS"`
	AdditionalProperties map[string]interface{}
}

type _CustomDnsServer CustomDnsServer

// NewCustomDnsServer instantiates a new CustomDnsServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomDnsServer(address string, isTLS bool) *CustomDnsServer {
	this := CustomDnsServer{}
	this.Address = address
	this.IsTLS = isTLS
	return &this
}

// NewCustomDnsServerWithDefaults instantiates a new CustomDnsServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomDnsServerWithDefaults() *CustomDnsServer {
	this := CustomDnsServer{}
	return &this
}

// GetAddress returns the Address field value
func (o *CustomDnsServer) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *CustomDnsServer) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *CustomDnsServer) SetAddress(v string) {
	o.Address = v
}

// GetIsTLS returns the IsTLS field value
func (o *CustomDnsServer) GetIsTLS() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTLS
}

// GetIsTLSOk returns a tuple with the IsTLS field value
// and a boolean to check if the value has been set.
func (o *CustomDnsServer) GetIsTLSOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTLS, true
}

// SetIsTLS sets field value
func (o *CustomDnsServer) SetIsTLS(v bool) {
	o.IsTLS = v
}

func (o CustomDnsServer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomDnsServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["isTLS"] = o.IsTLS

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomDnsServer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"isTLS",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomDnsServer := _CustomDnsServer{}

	err = json.Unmarshal(data, &varCustomDnsServer)

	if err != nil {
		return err
	}

	*o = CustomDnsServer(varCustomDnsServer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "isTLS")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomDnsServer struct {
	value *CustomDnsServer
	isSet bool
}

func (v NullableCustomDnsServer) Get() *CustomDnsServer {
	return v.value
}

func (v *NullableCustomDnsServer) Set(val *CustomDnsServer) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomDnsServer) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomDnsServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomDnsServer(val *CustomDnsServer) *NullableCustomDnsServer {
	return &NullableCustomDnsServer{value: val, isSet: true}
}

func (v NullableCustomDnsServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomDnsServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


