/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GumCustomRoleCategoriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GumCustomRoleCategoriesResponse{}

// GumCustomRoleCategoriesResponse struct for GumCustomRoleCategoriesResponse
type GumCustomRoleCategoriesResponse struct {
	Data []PermissionCategory `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _GumCustomRoleCategoriesResponse GumCustomRoleCategoriesResponse

// NewGumCustomRoleCategoriesResponse instantiates a new GumCustomRoleCategoriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGumCustomRoleCategoriesResponse(data []PermissionCategory) *GumCustomRoleCategoriesResponse {
	this := GumCustomRoleCategoriesResponse{}
	this.Data = data
	return &this
}

// NewGumCustomRoleCategoriesResponseWithDefaults instantiates a new GumCustomRoleCategoriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGumCustomRoleCategoriesResponseWithDefaults() *GumCustomRoleCategoriesResponse {
	this := GumCustomRoleCategoriesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GumCustomRoleCategoriesResponse) GetData() []PermissionCategory {
	if o == nil {
		var ret []PermissionCategory
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GumCustomRoleCategoriesResponse) GetDataOk() ([]PermissionCategory, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GumCustomRoleCategoriesResponse) SetData(v []PermissionCategory) {
	o.Data = v
}

func (o GumCustomRoleCategoriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GumCustomRoleCategoriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GumCustomRoleCategoriesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGumCustomRoleCategoriesResponse := _GumCustomRoleCategoriesResponse{}

	err = json.Unmarshal(data, &varGumCustomRoleCategoriesResponse)

	if err != nil {
		return err
	}

	*o = GumCustomRoleCategoriesResponse(varGumCustomRoleCategoriesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGumCustomRoleCategoriesResponse struct {
	value *GumCustomRoleCategoriesResponse
	isSet bool
}

func (v NullableGumCustomRoleCategoriesResponse) Get() *GumCustomRoleCategoriesResponse {
	return v.value
}

func (v *NullableGumCustomRoleCategoriesResponse) Set(val *GumCustomRoleCategoriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGumCustomRoleCategoriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGumCustomRoleCategoriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGumCustomRoleCategoriesResponse(val *GumCustomRoleCategoriesResponse) *NullableGumCustomRoleCategoriesResponse {
	return &NullableGumCustomRoleCategoriesResponse{value: val, isSet: true}
}

func (v NullableGumCustomRoleCategoriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGumCustomRoleCategoriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


