/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the IPSecPhaseConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecPhaseConfig{}

// IPSecPhaseConfig struct for IPSecPhaseConfig
type IPSecPhaseConfig struct {
	Auth []string `json:"auth"`
	Encryption []string `json:"encryption"`
	// Diffie Helman encryption
	Dh []int32 `json:"dh"`
	AdditionalProperties map[string]interface{}
}

type _IPSecPhaseConfig IPSecPhaseConfig

// NewIPSecPhaseConfig instantiates a new IPSecPhaseConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecPhaseConfig(auth []string, encryption []string, dh []int32) *IPSecPhaseConfig {
	this := IPSecPhaseConfig{}
	this.Auth = auth
	this.Encryption = encryption
	this.Dh = dh
	return &this
}

// NewIPSecPhaseConfigWithDefaults instantiates a new IPSecPhaseConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecPhaseConfigWithDefaults() *IPSecPhaseConfig {
	this := IPSecPhaseConfig{}
	return &this
}

// GetAuth returns the Auth field value
func (o *IPSecPhaseConfig) GetAuth() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Auth
}

// GetAuthOk returns a tuple with the Auth field value
// and a boolean to check if the value has been set.
func (o *IPSecPhaseConfig) GetAuthOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Auth, true
}

// SetAuth sets field value
func (o *IPSecPhaseConfig) SetAuth(v []string) {
	o.Auth = v
}

// GetEncryption returns the Encryption field value
func (o *IPSecPhaseConfig) GetEncryption() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Encryption
}

// GetEncryptionOk returns a tuple with the Encryption field value
// and a boolean to check if the value has been set.
func (o *IPSecPhaseConfig) GetEncryptionOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Encryption, true
}

// SetEncryption sets field value
func (o *IPSecPhaseConfig) SetEncryption(v []string) {
	o.Encryption = v
}

// GetDh returns the Dh field value
func (o *IPSecPhaseConfig) GetDh() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Dh
}

// GetDhOk returns a tuple with the Dh field value
// and a boolean to check if the value has been set.
func (o *IPSecPhaseConfig) GetDhOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dh, true
}

// SetDh sets field value
func (o *IPSecPhaseConfig) SetDh(v []int32) {
	o.Dh = v
}

func (o IPSecPhaseConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecPhaseConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auth"] = o.Auth
	toSerialize["encryption"] = o.Encryption
	toSerialize["dh"] = o.Dh

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPSecPhaseConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auth",
		"encryption",
		"dh",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPSecPhaseConfig := _IPSecPhaseConfig{}

	err = json.Unmarshal(data, &varIPSecPhaseConfig)

	if err != nil {
		return err
	}

	*o = IPSecPhaseConfig(varIPSecPhaseConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "auth")
		delete(additionalProperties, "encryption")
		delete(additionalProperties, "dh")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIPSecPhaseConfig struct {
	value *IPSecPhaseConfig
	isSet bool
}

func (v NullableIPSecPhaseConfig) Get() *IPSecPhaseConfig {
	return v.value
}

func (v *NullableIPSecPhaseConfig) Set(val *IPSecPhaseConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecPhaseConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecPhaseConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecPhaseConfig(val *IPSecPhaseConfig) *NullableIPSecPhaseConfig {
	return &NullableIPSecPhaseConfig{value: val, isSet: true}
}

func (v NullableIPSecPhaseConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecPhaseConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


