/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GumRoleAssignedUsersErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GumRoleAssignedUsersErrorResponse{}

// GumRoleAssignedUsersErrorResponse struct for GumRoleAssignedUsersErrorResponse
type GumRoleAssignedUsersErrorResponse struct {
	Error string `json:"error"`
	Message string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _GumRoleAssignedUsersErrorResponse GumRoleAssignedUsersErrorResponse

// NewGumRoleAssignedUsersErrorResponse instantiates a new GumRoleAssignedUsersErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGumRoleAssignedUsersErrorResponse(error_ string, message string) *GumRoleAssignedUsersErrorResponse {
	this := GumRoleAssignedUsersErrorResponse{}
	this.Error = error_
	this.Message = message
	return &this
}

// NewGumRoleAssignedUsersErrorResponseWithDefaults instantiates a new GumRoleAssignedUsersErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGumRoleAssignedUsersErrorResponseWithDefaults() *GumRoleAssignedUsersErrorResponse {
	this := GumRoleAssignedUsersErrorResponse{}
	return &this
}

// GetError returns the Error field value
func (o *GumRoleAssignedUsersErrorResponse) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *GumRoleAssignedUsersErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *GumRoleAssignedUsersErrorResponse) SetError(v string) {
	o.Error = v
}

// GetMessage returns the Message field value
func (o *GumRoleAssignedUsersErrorResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GumRoleAssignedUsersErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GumRoleAssignedUsersErrorResponse) SetMessage(v string) {
	o.Message = v
}

func (o GumRoleAssignedUsersErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GumRoleAssignedUsersErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GumRoleAssignedUsersErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGumRoleAssignedUsersErrorResponse := _GumRoleAssignedUsersErrorResponse{}

	err = json.Unmarshal(data, &varGumRoleAssignedUsersErrorResponse)

	if err != nil {
		return err
	}

	*o = GumRoleAssignedUsersErrorResponse(varGumRoleAssignedUsersErrorResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGumRoleAssignedUsersErrorResponse struct {
	value *GumRoleAssignedUsersErrorResponse
	isSet bool
}

func (v NullableGumRoleAssignedUsersErrorResponse) Get() *GumRoleAssignedUsersErrorResponse {
	return v.value
}

func (v *NullableGumRoleAssignedUsersErrorResponse) Set(val *GumRoleAssignedUsersErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGumRoleAssignedUsersErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGumRoleAssignedUsersErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGumRoleAssignedUsersErrorResponse(val *GumRoleAssignedUsersErrorResponse) *NullableGumRoleAssignedUsersErrorResponse {
	return &NullableGumRoleAssignedUsersErrorResponse{value: val, isSet: true}
}

func (v NullableGumRoleAssignedUsersErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGumRoleAssignedUsersErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


