/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomDnsUpdateAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomDnsUpdateAttributes{}

// CustomDnsUpdateAttributes Private DNS attributes for update (PUT) requests. Both `servers` and `searchDomains` are required (send `searchDomains: []` if you have none). Updates fully replace the attributes object, so send every field you want to keep; omitted fields are cleared. 
type CustomDnsUpdateAttributes struct {
	// Private DNS servers. Required, and must contain at least one entry when enabled is true.
	Servers []CustomDnsServer `json:"servers"`
	// DNS search domains. Required — send an empty array if you have none. Omitting it on update is rejected with 400; a non-empty value fully replaces any existing search domains.
	SearchDomains []string `json:"searchDomains"`
	DnsPolicy *DnsPolicy `json:"dnsPolicy,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomDnsUpdateAttributes CustomDnsUpdateAttributes

// NewCustomDnsUpdateAttributes instantiates a new CustomDnsUpdateAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomDnsUpdateAttributes(servers []CustomDnsServer, searchDomains []string) *CustomDnsUpdateAttributes {
	this := CustomDnsUpdateAttributes{}
	this.Servers = servers
	this.SearchDomains = searchDomains
	return &this
}

// NewCustomDnsUpdateAttributesWithDefaults instantiates a new CustomDnsUpdateAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomDnsUpdateAttributesWithDefaults() *CustomDnsUpdateAttributes {
	this := CustomDnsUpdateAttributes{}
	return &this
}

// GetServers returns the Servers field value
func (o *CustomDnsUpdateAttributes) GetServers() []CustomDnsServer {
	if o == nil {
		var ret []CustomDnsServer
		return ret
	}

	return o.Servers
}

// GetServersOk returns a tuple with the Servers field value
// and a boolean to check if the value has been set.
func (o *CustomDnsUpdateAttributes) GetServersOk() ([]CustomDnsServer, bool) {
	if o == nil {
		return nil, false
	}
	return o.Servers, true
}

// SetServers sets field value
func (o *CustomDnsUpdateAttributes) SetServers(v []CustomDnsServer) {
	o.Servers = v
}

// GetSearchDomains returns the SearchDomains field value
func (o *CustomDnsUpdateAttributes) GetSearchDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SearchDomains
}

// GetSearchDomainsOk returns a tuple with the SearchDomains field value
// and a boolean to check if the value has been set.
func (o *CustomDnsUpdateAttributes) GetSearchDomainsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SearchDomains, true
}

// SetSearchDomains sets field value
func (o *CustomDnsUpdateAttributes) SetSearchDomains(v []string) {
	o.SearchDomains = v
}

// GetDnsPolicy returns the DnsPolicy field value if set, zero value otherwise.
func (o *CustomDnsUpdateAttributes) GetDnsPolicy() DnsPolicy {
	if o == nil || IsNil(o.DnsPolicy) {
		var ret DnsPolicy
		return ret
	}
	return *o.DnsPolicy
}

// GetDnsPolicyOk returns a tuple with the DnsPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomDnsUpdateAttributes) GetDnsPolicyOk() (*DnsPolicy, bool) {
	if o == nil || IsNil(o.DnsPolicy) {
		return nil, false
	}
	return o.DnsPolicy, true
}

// HasDnsPolicy returns a boolean if a field has been set.
func (o *CustomDnsUpdateAttributes) HasDnsPolicy() bool {
	if o != nil && !IsNil(o.DnsPolicy) {
		return true
	}

	return false
}

// SetDnsPolicy gets a reference to the given DnsPolicy and assigns it to the DnsPolicy field.
func (o *CustomDnsUpdateAttributes) SetDnsPolicy(v DnsPolicy) {
	o.DnsPolicy = &v
}

func (o CustomDnsUpdateAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomDnsUpdateAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["servers"] = o.Servers
	toSerialize["searchDomains"] = o.SearchDomains
	if !IsNil(o.DnsPolicy) {
		toSerialize["dnsPolicy"] = o.DnsPolicy
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomDnsUpdateAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"servers",
		"searchDomains",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomDnsUpdateAttributes := _CustomDnsUpdateAttributes{}

	err = json.Unmarshal(data, &varCustomDnsUpdateAttributes)

	if err != nil {
		return err
	}

	*o = CustomDnsUpdateAttributes(varCustomDnsUpdateAttributes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "servers")
		delete(additionalProperties, "searchDomains")
		delete(additionalProperties, "dnsPolicy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomDnsUpdateAttributes struct {
	value *CustomDnsUpdateAttributes
	isSet bool
}

func (v NullableCustomDnsUpdateAttributes) Get() *CustomDnsUpdateAttributes {
	return v.value
}

func (v *NullableCustomDnsUpdateAttributes) Set(val *CustomDnsUpdateAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomDnsUpdateAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomDnsUpdateAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomDnsUpdateAttributes(val *CustomDnsUpdateAttributes) *NullableCustomDnsUpdateAttributes {
	return &NullableCustomDnsUpdateAttributes{value: val, isSet: true}
}

func (v NullableCustomDnsUpdateAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomDnsUpdateAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


