/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the IPSecSharedSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecSharedSettings{}

// IPSecSharedSettings struct for IPSecSharedSettings
type IPSecSharedSettings struct {
	P81GatewaySubnets []string `json:"p81GatewaySubnets"`
	RemoteGatewaySubnets []string `json:"remoteGatewaySubnets"`
	P81ASN *int32 `json:"p81ASN,omitempty"`
	Features *IPSecSharedSettingsFeatures `json:"features,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IPSecSharedSettings IPSecSharedSettings

// NewIPSecSharedSettings instantiates a new IPSecSharedSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecSharedSettings(p81GatewaySubnets []string, remoteGatewaySubnets []string) *IPSecSharedSettings {
	this := IPSecSharedSettings{}
	this.P81GatewaySubnets = p81GatewaySubnets
	this.RemoteGatewaySubnets = remoteGatewaySubnets
	return &this
}

// NewIPSecSharedSettingsWithDefaults instantiates a new IPSecSharedSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecSharedSettingsWithDefaults() *IPSecSharedSettings {
	this := IPSecSharedSettings{}
	return &this
}

// GetP81GatewaySubnets returns the P81GatewaySubnets field value
func (o *IPSecSharedSettings) GetP81GatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.P81GatewaySubnets
}

// GetP81GatewaySubnetsOk returns a tuple with the P81GatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettings) GetP81GatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.P81GatewaySubnets, true
}

// SetP81GatewaySubnets sets field value
func (o *IPSecSharedSettings) SetP81GatewaySubnets(v []string) {
	o.P81GatewaySubnets = v
}

// GetRemoteGatewaySubnets returns the RemoteGatewaySubnets field value
func (o *IPSecSharedSettings) GetRemoteGatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemoteGatewaySubnets
}

// GetRemoteGatewaySubnetsOk returns a tuple with the RemoteGatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettings) GetRemoteGatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGatewaySubnets, true
}

// SetRemoteGatewaySubnets sets field value
func (o *IPSecSharedSettings) SetRemoteGatewaySubnets(v []string) {
	o.RemoteGatewaySubnets = v
}

// GetP81ASN returns the P81ASN field value if set, zero value otherwise.
func (o *IPSecSharedSettings) GetP81ASN() int32 {
	if o == nil || IsNil(o.P81ASN) {
		var ret int32
		return ret
	}
	return *o.P81ASN
}

// GetP81ASNOk returns a tuple with the P81ASN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettings) GetP81ASNOk() (*int32, bool) {
	if o == nil || IsNil(o.P81ASN) {
		return nil, false
	}
	return o.P81ASN, true
}

// HasP81ASN returns a boolean if a field has been set.
func (o *IPSecSharedSettings) HasP81ASN() bool {
	if o != nil && !IsNil(o.P81ASN) {
		return true
	}

	return false
}

// SetP81ASN gets a reference to the given int32 and assigns it to the P81ASN field.
func (o *IPSecSharedSettings) SetP81ASN(v int32) {
	o.P81ASN = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *IPSecSharedSettings) GetFeatures() IPSecSharedSettingsFeatures {
	if o == nil || IsNil(o.Features) {
		var ret IPSecSharedSettingsFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettings) GetFeaturesOk() (*IPSecSharedSettingsFeatures, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *IPSecSharedSettings) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given IPSecSharedSettingsFeatures and assigns it to the Features field.
func (o *IPSecSharedSettings) SetFeatures(v IPSecSharedSettingsFeatures) {
	o.Features = &v
}

func (o IPSecSharedSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecSharedSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["p81GatewaySubnets"] = o.P81GatewaySubnets
	toSerialize["remoteGatewaySubnets"] = o.RemoteGatewaySubnets
	if !IsNil(o.P81ASN) {
		toSerialize["p81ASN"] = o.P81ASN
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IPSecSharedSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"p81GatewaySubnets",
		"remoteGatewaySubnets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPSecSharedSettings := _IPSecSharedSettings{}

	err = json.Unmarshal(data, &varIPSecSharedSettings)

	if err != nil {
		return err
	}

	*o = IPSecSharedSettings(varIPSecSharedSettings)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "p81GatewaySubnets")
		delete(additionalProperties, "remoteGatewaySubnets")
		delete(additionalProperties, "p81ASN")
		delete(additionalProperties, "features")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIPSecSharedSettings struct {
	value *IPSecSharedSettings
	isSet bool
}

func (v NullableIPSecSharedSettings) Get() *IPSecSharedSettings {
	return v.value
}

func (v *NullableIPSecSharedSettings) Set(val *IPSecSharedSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecSharedSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecSharedSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecSharedSettings(val *IPSecSharedSettings) *NullableIPSecSharedSettings {
	return &NullableIPSecSharedSettings{value: val, isSet: true}
}

func (v NullableIPSecSharedSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecSharedSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


