/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech).
//
// HAND-MAINTAINED, NOT REGENERATED: this file is listed in
// .openapi-generator-ignore. UnmarshalJSON below carries a fix for
// P81-145279 that the spec cannot express (see its own comment) and must
// survive `generate.sh`. Everything else in this file is stock generator
// output as of the last regeneration and may drift if the schema changes --
// diff against a throwaway regeneration before trusting it blindly.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AccessPolicySource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessPolicySource{}

// AccessPolicySource Source definition for access policy rules
type AccessPolicySource struct {
	Type string `json:"type"`
	// Array of IDs (strings)
	Value []string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _AccessPolicySource AccessPolicySource

// NewAccessPolicySource instantiates a new AccessPolicySource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessPolicySource(type_ string, value []string) *AccessPolicySource {
	this := AccessPolicySource{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewAccessPolicySourceWithDefaults instantiates a new AccessPolicySource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessPolicySourceWithDefaults() *AccessPolicySource {
	this := AccessPolicySource{}
	return &this
}

// GetType returns the Type field value
func (o *AccessPolicySource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccessPolicySource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccessPolicySource) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *AccessPolicySource) GetValue() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AccessPolicySource) GetValueOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *AccessPolicySource) SetValue(v []string) {
	o.Value = v
}

func (o AccessPolicySource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessPolicySource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccessPolicySource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	// P81-145279: the spec declares `value` as an array of ID strings, and
	// that is what a WRITE sends -- but once the server canonicalises an
	// "addresses"-type source, the READ/write-response `value` array holds
	// OBJECTS instead (`{"sharedObjectId":"BxOZLWBEGQ","type":"address",
	// "value":["10.99.0.31"],"ipVersion":"ipv4","valueType":"ip"}`), measured
	// on a successful (200) UpdateAccessPolicy response. json.Unmarshal into
	// []string fails outright on that shape, which turned a successful write
	// into a reported failure (resource_access_policy.go's "Unable to write
	// the tenant's web access policy"). Reduce every element to the id string
	// GetValue() has always promised -- generically, before the strict
	// struct decode below ever sees the field -- rather than widen Value's
	// type and ripple that into every caller that only ever wanted the id.
	rawValues, ok := allProperties["value"].([]interface{})
	if !ok {
		return fmt.Errorf("access policy source value: expected an array, got %T", allProperties["value"])
	}
	ids := make([]string, len(rawValues))
	for i, raw := range rawValues {
		switch v := raw.(type) {
		case string:
			ids[i] = v
		case map[string]interface{}:
			id, ok := v["sharedObjectId"].(string)
			if !ok {
				return fmt.Errorf("access policy source value[%d]: object has no string sharedObjectId", i)
			}
			ids[i] = id
		default:
			return fmt.Errorf("access policy source value[%d]: unexpected type %T", i, raw)
		}
	}
	// varAccessPolicySource is decoded from allProperties with "value" removed
	// rather than from the original `data`, so the struct decode below never
	// re-encounters the shape that just broke it above.
	delete(allProperties, "value")
	strippedData, err := json.Marshal(allProperties)
	if err != nil {
		return err
	}

	varAccessPolicySource := _AccessPolicySource{}

	err = json.Unmarshal(strippedData, &varAccessPolicySource)

	if err != nil {
		return err
	}

	varAccessPolicySource.Value = ids

	*o = AccessPolicySource(varAccessPolicySource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccessPolicySource struct {
	value *AccessPolicySource
	isSet bool
}

func (v NullableAccessPolicySource) Get() *AccessPolicySource {
	return v.value
}

func (v *NullableAccessPolicySource) Set(val *AccessPolicySource) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessPolicySource) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessPolicySource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessPolicySource(val *AccessPolicySource) *NullableAccessPolicySource {
	return &NullableAccessPolicySource{value: val, isSet: true}
}

func (v NullableAccessPolicySource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessPolicySource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


