/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the UserProfileDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProfileDto{}

// UserProfileDto struct for UserProfileDto
type UserProfileDto struct {
	FirstName *string `json:"firstName,omitempty" validate:"regexp=^[a-zA-Z '-]+$"`
	LastName *string `json:"lastName,omitempty" validate:"regexp=^[a-zA-Z '-]+$"`
	RoleName *string `json:"roleName,omitempty"`
	Phone *string `json:"phone,omitempty" validate:"regexp=^\\+?[0-9]{9\\,15}$"`
	AdditionalProperties map[string]interface{}
}

type _UserProfileDto UserProfileDto

// NewUserProfileDto instantiates a new UserProfileDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProfileDto() *UserProfileDto {
	this := UserProfileDto{}
	var roleName string = ""
	this.RoleName = &roleName
	return &this
}

// NewUserProfileDtoWithDefaults instantiates a new UserProfileDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProfileDtoWithDefaults() *UserProfileDto {
	this := UserProfileDto{}
	var roleName string = ""
	this.RoleName = &roleName
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserProfileDto) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileDto) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserProfileDto) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserProfileDto) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserProfileDto) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileDto) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserProfileDto) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserProfileDto) SetLastName(v string) {
	o.LastName = &v
}

// GetRoleName returns the RoleName field value if set, zero value otherwise.
func (o *UserProfileDto) GetRoleName() string {
	if o == nil || IsNil(o.RoleName) {
		var ret string
		return ret
	}
	return *o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileDto) GetRoleNameOk() (*string, bool) {
	if o == nil || IsNil(o.RoleName) {
		return nil, false
	}
	return o.RoleName, true
}

// HasRoleName returns a boolean if a field has been set.
func (o *UserProfileDto) HasRoleName() bool {
	if o != nil && !IsNil(o.RoleName) {
		return true
	}

	return false
}

// SetRoleName gets a reference to the given string and assigns it to the RoleName field.
func (o *UserProfileDto) SetRoleName(v string) {
	o.RoleName = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *UserProfileDto) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileDto) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *UserProfileDto) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *UserProfileDto) SetPhone(v string) {
	o.Phone = &v
}

func (o UserProfileDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProfileDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.RoleName) {
		toSerialize["roleName"] = o.RoleName
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserProfileDto) UnmarshalJSON(data []byte) (err error) {
	varUserProfileDto := _UserProfileDto{}

	err = json.Unmarshal(data, &varUserProfileDto)

	if err != nil {
		return err
	}

	*o = UserProfileDto(varUserProfileDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "roleName")
		delete(additionalProperties, "phone")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserProfileDto struct {
	value *UserProfileDto
	isSet bool
}

func (v NullableUserProfileDto) Get() *UserProfileDto {
	return v.value
}

func (v *NullableUserProfileDto) Set(val *UserProfileDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfileDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfileDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfileDto(val *UserProfileDto) *NullableUserProfileDto {
	return &NullableUserProfileDto{value: val, isSet: true}
}

func (v NullableUserProfileDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfileDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


