/*
Check Point - SASE Public API

The YAML for Check Points SASE Public API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the EnhancedTunnelBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedTunnelBase{}

// EnhancedTunnelBase struct for EnhancedTunnelBase
type EnhancedTunnelBase struct {
	// Authentication type for tunnel (psk for pre-shared key, cert for certificate)
	AuthType string `json:"authType"`
	// Pre-shared key for tunnel authentication (8-64 characters). Required when authType is psk.
	Passphrase *string `json:"passphrase,omitempty"`
	// Customer root certificate authority. Required when authType is cert.
	CustomerRootCA *string `json:"customerRootCA,omitempty"`
	// Target region ID
	RegionID string `json:"regionID"`
	// Name of the static tunnel
	TunnelName string `json:"tunnelName"`
	// Harmony Sase gateway subnets
	P81GatewaySubnets []string `json:"p81GatewaySubnets"`
	// Remote gateway subnets
	RemoteGatewaySubnets []string `json:"remoteGatewaySubnets"`
	// IKE version for key exchange
	KeyExchange string `json:"keyExchange"`
	AdvancedSettings *IPSecAdvancedSettingsV23 `json:"advancedSettings,omitempty"`
	RoutingType *RoutingType `json:"routingType,omitempty"`
	// Expected peak throughput of the tunnel communication in Mbps. Typical connection will be of 1000Mbps.
	PeakBandwidthMbps *int32 `json:"peakBandwidthMbps,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EnhancedTunnelBase EnhancedTunnelBase

// NewEnhancedTunnelBase instantiates a new EnhancedTunnelBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedTunnelBase(authType string, regionID string, tunnelName string, p81GatewaySubnets []string, remoteGatewaySubnets []string, keyExchange string) *EnhancedTunnelBase {
	this := EnhancedTunnelBase{}
	this.AuthType = authType
	this.RegionID = regionID
	this.TunnelName = tunnelName
	this.P81GatewaySubnets = p81GatewaySubnets
	this.RemoteGatewaySubnets = remoteGatewaySubnets
	this.KeyExchange = keyExchange
	var routingType RoutingType = ROUTINGTYPE_ROUTE
	this.RoutingType = &routingType
	var peakBandwidthMbps int32 = 1000
	this.PeakBandwidthMbps = &peakBandwidthMbps
	return &this
}

// NewEnhancedTunnelBaseWithDefaults instantiates a new EnhancedTunnelBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedTunnelBaseWithDefaults() *EnhancedTunnelBase {
	this := EnhancedTunnelBase{}
	var keyExchange string = "ikev2"
	this.KeyExchange = keyExchange
	var routingType RoutingType = ROUTINGTYPE_ROUTE
	this.RoutingType = &routingType
	var peakBandwidthMbps int32 = 1000
	this.PeakBandwidthMbps = &peakBandwidthMbps
	return &this
}

// GetAuthType returns the AuthType field value
func (o *EnhancedTunnelBase) GetAuthType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *EnhancedTunnelBase) SetAuthType(v string) {
	o.AuthType = v
}

// GetPassphrase returns the Passphrase field value if set, zero value otherwise.
func (o *EnhancedTunnelBase) GetPassphrase() string {
	if o == nil || IsNil(o.Passphrase) {
		var ret string
		return ret
	}
	return *o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetPassphraseOk() (*string, bool) {
	if o == nil || IsNil(o.Passphrase) {
		return nil, false
	}
	return o.Passphrase, true
}

// HasPassphrase returns a boolean if a field has been set.
func (o *EnhancedTunnelBase) HasPassphrase() bool {
	if o != nil && !IsNil(o.Passphrase) {
		return true
	}

	return false
}

// SetPassphrase gets a reference to the given string and assigns it to the Passphrase field.
func (o *EnhancedTunnelBase) SetPassphrase(v string) {
	o.Passphrase = &v
}

// GetCustomerRootCA returns the CustomerRootCA field value if set, zero value otherwise.
func (o *EnhancedTunnelBase) GetCustomerRootCA() string {
	if o == nil || IsNil(o.CustomerRootCA) {
		var ret string
		return ret
	}
	return *o.CustomerRootCA
}

// GetCustomerRootCAOk returns a tuple with the CustomerRootCA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetCustomerRootCAOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerRootCA) {
		return nil, false
	}
	return o.CustomerRootCA, true
}

// HasCustomerRootCA returns a boolean if a field has been set.
func (o *EnhancedTunnelBase) HasCustomerRootCA() bool {
	if o != nil && !IsNil(o.CustomerRootCA) {
		return true
	}

	return false
}

// SetCustomerRootCA gets a reference to the given string and assigns it to the CustomerRootCA field.
func (o *EnhancedTunnelBase) SetCustomerRootCA(v string) {
	o.CustomerRootCA = &v
}

// GetRegionID returns the RegionID field value
func (o *EnhancedTunnelBase) GetRegionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionID
}

// GetRegionIDOk returns a tuple with the RegionID field value
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetRegionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionID, true
}

// SetRegionID sets field value
func (o *EnhancedTunnelBase) SetRegionID(v string) {
	o.RegionID = v
}

// GetTunnelName returns the TunnelName field value
func (o *EnhancedTunnelBase) GetTunnelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetTunnelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelName, true
}

// SetTunnelName sets field value
func (o *EnhancedTunnelBase) SetTunnelName(v string) {
	o.TunnelName = v
}

// GetP81GatewaySubnets returns the P81GatewaySubnets field value
func (o *EnhancedTunnelBase) GetP81GatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.P81GatewaySubnets
}

// GetP81GatewaySubnetsOk returns a tuple with the P81GatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetP81GatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.P81GatewaySubnets, true
}

// SetP81GatewaySubnets sets field value
func (o *EnhancedTunnelBase) SetP81GatewaySubnets(v []string) {
	o.P81GatewaySubnets = v
}

// GetRemoteGatewaySubnets returns the RemoteGatewaySubnets field value
func (o *EnhancedTunnelBase) GetRemoteGatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemoteGatewaySubnets
}

// GetRemoteGatewaySubnetsOk returns a tuple with the RemoteGatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetRemoteGatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGatewaySubnets, true
}

// SetRemoteGatewaySubnets sets field value
func (o *EnhancedTunnelBase) SetRemoteGatewaySubnets(v []string) {
	o.RemoteGatewaySubnets = v
}

// GetKeyExchange returns the KeyExchange field value
func (o *EnhancedTunnelBase) GetKeyExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetKeyExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyExchange, true
}

// SetKeyExchange sets field value
func (o *EnhancedTunnelBase) SetKeyExchange(v string) {
	o.KeyExchange = v
}

// GetAdvancedSettings returns the AdvancedSettings field value if set, zero value otherwise.
func (o *EnhancedTunnelBase) GetAdvancedSettings() IPSecAdvancedSettingsV23 {
	if o == nil || IsNil(o.AdvancedSettings) {
		var ret IPSecAdvancedSettingsV23
		return ret
	}
	return *o.AdvancedSettings
}

// GetAdvancedSettingsOk returns a tuple with the AdvancedSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetAdvancedSettingsOk() (*IPSecAdvancedSettingsV23, bool) {
	if o == nil || IsNil(o.AdvancedSettings) {
		return nil, false
	}
	return o.AdvancedSettings, true
}

// HasAdvancedSettings returns a boolean if a field has been set.
func (o *EnhancedTunnelBase) HasAdvancedSettings() bool {
	if o != nil && !IsNil(o.AdvancedSettings) {
		return true
	}

	return false
}

// SetAdvancedSettings gets a reference to the given IPSecAdvancedSettingsV23 and assigns it to the AdvancedSettings field.
func (o *EnhancedTunnelBase) SetAdvancedSettings(v IPSecAdvancedSettingsV23) {
	o.AdvancedSettings = &v
}

// GetRoutingType returns the RoutingType field value if set, zero value otherwise.
func (o *EnhancedTunnelBase) GetRoutingType() RoutingType {
	if o == nil || IsNil(o.RoutingType) {
		var ret RoutingType
		return ret
	}
	return *o.RoutingType
}

// GetRoutingTypeOk returns a tuple with the RoutingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetRoutingTypeOk() (*RoutingType, bool) {
	if o == nil || IsNil(o.RoutingType) {
		return nil, false
	}
	return o.RoutingType, true
}

// HasRoutingType returns a boolean if a field has been set.
func (o *EnhancedTunnelBase) HasRoutingType() bool {
	if o != nil && !IsNil(o.RoutingType) {
		return true
	}

	return false
}

// SetRoutingType gets a reference to the given RoutingType and assigns it to the RoutingType field.
func (o *EnhancedTunnelBase) SetRoutingType(v RoutingType) {
	o.RoutingType = &v
}

// GetPeakBandwidthMbps returns the PeakBandwidthMbps field value if set, zero value otherwise.
func (o *EnhancedTunnelBase) GetPeakBandwidthMbps() int32 {
	if o == nil || IsNil(o.PeakBandwidthMbps) {
		var ret int32
		return ret
	}
	return *o.PeakBandwidthMbps
}

// GetPeakBandwidthMbpsOk returns a tuple with the PeakBandwidthMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedTunnelBase) GetPeakBandwidthMbpsOk() (*int32, bool) {
	if o == nil || IsNil(o.PeakBandwidthMbps) {
		return nil, false
	}
	return o.PeakBandwidthMbps, true
}

// HasPeakBandwidthMbps returns a boolean if a field has been set.
func (o *EnhancedTunnelBase) HasPeakBandwidthMbps() bool {
	if o != nil && !IsNil(o.PeakBandwidthMbps) {
		return true
	}

	return false
}

// SetPeakBandwidthMbps gets a reference to the given int32 and assigns it to the PeakBandwidthMbps field.
func (o *EnhancedTunnelBase) SetPeakBandwidthMbps(v int32) {
	o.PeakBandwidthMbps = &v
}

func (o EnhancedTunnelBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedTunnelBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authType"] = o.AuthType
	if !IsNil(o.Passphrase) {
		toSerialize["passphrase"] = o.Passphrase
	}
	if !IsNil(o.CustomerRootCA) {
		toSerialize["customerRootCA"] = o.CustomerRootCA
	}
	toSerialize["regionID"] = o.RegionID
	toSerialize["tunnelName"] = o.TunnelName
	toSerialize["p81GatewaySubnets"] = o.P81GatewaySubnets
	toSerialize["remoteGatewaySubnets"] = o.RemoteGatewaySubnets
	toSerialize["keyExchange"] = o.KeyExchange
	if !IsNil(o.AdvancedSettings) {
		toSerialize["advancedSettings"] = o.AdvancedSettings
	}
	if !IsNil(o.RoutingType) {
		toSerialize["routingType"] = o.RoutingType
	}
	if !IsNil(o.PeakBandwidthMbps) {
		toSerialize["peakBandwidthMbps"] = o.PeakBandwidthMbps
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EnhancedTunnelBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authType",
		"regionID",
		"tunnelName",
		"p81GatewaySubnets",
		"remoteGatewaySubnets",
		"keyExchange",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnhancedTunnelBase := _EnhancedTunnelBase{}

	err = json.Unmarshal(data, &varEnhancedTunnelBase)

	if err != nil {
		return err
	}

	*o = EnhancedTunnelBase(varEnhancedTunnelBase)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authType")
		delete(additionalProperties, "passphrase")
		delete(additionalProperties, "customerRootCA")
		delete(additionalProperties, "regionID")
		delete(additionalProperties, "tunnelName")
		delete(additionalProperties, "p81GatewaySubnets")
		delete(additionalProperties, "remoteGatewaySubnets")
		delete(additionalProperties, "keyExchange")
		delete(additionalProperties, "advancedSettings")
		delete(additionalProperties, "routingType")
		delete(additionalProperties, "peakBandwidthMbps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEnhancedTunnelBase struct {
	value *EnhancedTunnelBase
	isSet bool
}

func (v NullableEnhancedTunnelBase) Get() *EnhancedTunnelBase {
	return v.value
}

func (v *NullableEnhancedTunnelBase) Set(val *EnhancedTunnelBase) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedTunnelBase) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedTunnelBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedTunnelBase(val *EnhancedTunnelBase) *NullableEnhancedTunnelBase {
	return &NullableEnhancedTunnelBase{value: val, isSet: true}
}

func (v NullableEnhancedTunnelBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedTunnelBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


